version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "sunday"
          time: "16:00"

      labels:
          - "dependencies"
          - "github-actions"

      commit-message:
          prefix: "chore"
          include: "scope"

      groups:
          github-actions:
              patterns:
                  - "*"

    - package-ecosystem: "npm"
      directory: "/apps/backend"
      schedule:
          interval: "monthly"
      groups:
          nestjs:
              patterns:
                  - "@nestjs/*"
          prisma:
              patterns:
                  - "prisma"
                  - "@prisma/*"
          jest:
              patterns:
                  - "jest"
                  - "ts-jest"
                  - "@types/jest"

    - package-ecosystem: "npm"
      directory: "/apps/frontend"
      schedule:
          interval: "monthly"
      groups:
          react-stack:
              patterns:
                  - "react*"
                  - "@types/react*"
          tailwind:
              patterns:
                  - "tailwind*"
                  - "@tailwindcss/*"
