/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `InstanceSettings` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums.js";
import type * as Prisma from "../internal/prismaNamespace.js";

/**
 * Model InstanceSettings
 *
 */
export type InstanceSettingsModel =
    runtime.Types.Result.DefaultSelection<Prisma.$InstanceSettingsPayload>;

export type AggregateInstanceSettings = {
    _count: InstanceSettingsCountAggregateOutputType | null;
    _min: InstanceSettingsMinAggregateOutputType | null;
    _max: InstanceSettingsMaxAggregateOutputType | null;
};

export type InstanceSettingsMinAggregateOutputType = {
    id: string | null;
    openAIApiKey: string | null;
    openAIApiKeyEnabled: boolean | null;
    createdAt: Date | null;
    updatedAt: Date | null;
};

export type InstanceSettingsMaxAggregateOutputType = {
    id: string | null;
    openAIApiKey: string | null;
    openAIApiKeyEnabled: boolean | null;
    createdAt: Date | null;
    updatedAt: Date | null;
};

export type InstanceSettingsCountAggregateOutputType = {
    id: number;
    openAIApiKey: number;
    openAIApiKeyEnabled: number;
    createdAt: number;
    updatedAt: number;
    _all: number;
};

export type InstanceSettingsMinAggregateInputType = {
    id?: true;
    openAIApiKey?: true;
    openAIApiKeyEnabled?: true;
    createdAt?: true;
    updatedAt?: true;
};

export type InstanceSettingsMaxAggregateInputType = {
    id?: true;
    openAIApiKey?: true;
    openAIApiKeyEnabled?: true;
    createdAt?: true;
    updatedAt?: true;
};

export type InstanceSettingsCountAggregateInputType = {
    id?: true;
    openAIApiKey?: true;
    openAIApiKeyEnabled?: true;
    createdAt?: true;
    updatedAt?: true;
    _all?: true;
};

export type InstanceSettingsAggregateArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which InstanceSettings to aggregate.
     */
    where?: Prisma.InstanceSettingsWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of InstanceSettings to fetch.
     */
    orderBy?:
        | Prisma.InstanceSettingsOrderByWithRelationInput
        | Prisma.InstanceSettingsOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the start position
     */
    cursor?: Prisma.InstanceSettingsWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` InstanceSettings from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` InstanceSettings.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Count returned InstanceSettings
     **/
    _count?: true | InstanceSettingsCountAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the minimum value
     **/
    _min?: InstanceSettingsMinAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the maximum value
     **/
    _max?: InstanceSettingsMaxAggregateInputType;
};

export type GetInstanceSettingsAggregateType<
    T extends InstanceSettingsAggregateArgs,
> = {
    [P in keyof T & keyof AggregateInstanceSettings]: P extends
        | "_count"
        | "count"
        ? T[P] extends true
            ? number
            : Prisma.GetScalarType<T[P], AggregateInstanceSettings[P]>
        : Prisma.GetScalarType<T[P], AggregateInstanceSettings[P]>;
};

export type InstanceSettingsGroupByArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.InstanceSettingsWhereInput;
    orderBy?:
        | Prisma.InstanceSettingsOrderByWithAggregationInput
        | Prisma.InstanceSettingsOrderByWithAggregationInput[];
    by:
        | Prisma.InstanceSettingsScalarFieldEnum[]
        | Prisma.InstanceSettingsScalarFieldEnum;
    having?: Prisma.InstanceSettingsScalarWhereWithAggregatesInput;
    take?: number;
    skip?: number;
    _count?: InstanceSettingsCountAggregateInputType | true;
    _min?: InstanceSettingsMinAggregateInputType;
    _max?: InstanceSettingsMaxAggregateInputType;
};

export type InstanceSettingsGroupByOutputType = {
    id: string;
    openAIApiKey: string | null;
    openAIApiKeyEnabled: boolean;
    createdAt: Date;
    updatedAt: Date;
    _count: InstanceSettingsCountAggregateOutputType | null;
    _min: InstanceSettingsMinAggregateOutputType | null;
    _max: InstanceSettingsMaxAggregateOutputType | null;
};

type GetInstanceSettingsGroupByPayload<T extends InstanceSettingsGroupByArgs> =
    Prisma.PrismaPromise<
        Array<
            Prisma.PickEnumerable<
                InstanceSettingsGroupByOutputType,
                T["by"]
            > & {
                [P in keyof T &
                    keyof InstanceSettingsGroupByOutputType]: P extends "_count"
                    ? T[P] extends boolean
                        ? number
                        : Prisma.GetScalarType<
                              T[P],
                              InstanceSettingsGroupByOutputType[P]
                          >
                    : Prisma.GetScalarType<
                          T[P],
                          InstanceSettingsGroupByOutputType[P]
                      >;
            }
        >
    >;

export type InstanceSettingsWhereInput = {
    AND?:
        | Prisma.InstanceSettingsWhereInput
        | Prisma.InstanceSettingsWhereInput[];
    OR?: Prisma.InstanceSettingsWhereInput[];
    NOT?:
        | Prisma.InstanceSettingsWhereInput
        | Prisma.InstanceSettingsWhereInput[];
    id?: Prisma.StringFilter<"InstanceSettings"> | string;
    openAIApiKey?:
        | Prisma.StringNullableFilter<"InstanceSettings">
        | string
        | null;
    openAIApiKeyEnabled?: Prisma.BoolFilter<"InstanceSettings"> | boolean;
    createdAt?: Prisma.DateTimeFilter<"InstanceSettings"> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<"InstanceSettings"> | Date | string;
};

export type InstanceSettingsOrderByWithRelationInput = {
    id?: Prisma.SortOrder;
    openAIApiKey?: Prisma.SortOrderInput | Prisma.SortOrder;
    openAIApiKeyEnabled?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
};

export type InstanceSettingsWhereUniqueInput = Prisma.AtLeast<
    {
        id?: string;
        AND?:
            | Prisma.InstanceSettingsWhereInput
            | Prisma.InstanceSettingsWhereInput[];
        OR?: Prisma.InstanceSettingsWhereInput[];
        NOT?:
            | Prisma.InstanceSettingsWhereInput
            | Prisma.InstanceSettingsWhereInput[];
        openAIApiKey?:
            | Prisma.StringNullableFilter<"InstanceSettings">
            | string
            | null;
        openAIApiKeyEnabled?: Prisma.BoolFilter<"InstanceSettings"> | boolean;
        createdAt?: Prisma.DateTimeFilter<"InstanceSettings"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"InstanceSettings"> | Date | string;
    },
    "id"
>;

export type InstanceSettingsOrderByWithAggregationInput = {
    id?: Prisma.SortOrder;
    openAIApiKey?: Prisma.SortOrderInput | Prisma.SortOrder;
    openAIApiKeyEnabled?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
    _count?: Prisma.InstanceSettingsCountOrderByAggregateInput;
    _max?: Prisma.InstanceSettingsMaxOrderByAggregateInput;
    _min?: Prisma.InstanceSettingsMinOrderByAggregateInput;
};

export type InstanceSettingsScalarWhereWithAggregatesInput = {
    AND?:
        | Prisma.InstanceSettingsScalarWhereWithAggregatesInput
        | Prisma.InstanceSettingsScalarWhereWithAggregatesInput[];
    OR?: Prisma.InstanceSettingsScalarWhereWithAggregatesInput[];
    NOT?:
        | Prisma.InstanceSettingsScalarWhereWithAggregatesInput
        | Prisma.InstanceSettingsScalarWhereWithAggregatesInput[];
    id?: Prisma.StringWithAggregatesFilter<"InstanceSettings"> | string;
    openAIApiKey?:
        | Prisma.StringNullableWithAggregatesFilter<"InstanceSettings">
        | string
        | null;
    openAIApiKeyEnabled?:
        | Prisma.BoolWithAggregatesFilter<"InstanceSettings">
        | boolean;
    createdAt?:
        | Prisma.DateTimeWithAggregatesFilter<"InstanceSettings">
        | Date
        | string;
    updatedAt?:
        | Prisma.DateTimeWithAggregatesFilter<"InstanceSettings">
        | Date
        | string;
};

export type InstanceSettingsCreateInput = {
    id?: string;
    openAIApiKey?: string | null;
    openAIApiKeyEnabled?: boolean;
    createdAt?: Date | string;
    updatedAt?: Date | string;
};

export type InstanceSettingsUncheckedCreateInput = {
    id?: string;
    openAIApiKey?: string | null;
    openAIApiKeyEnabled?: boolean;
    createdAt?: Date | string;
    updatedAt?: Date | string;
};

export type InstanceSettingsUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    openAIApiKey?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    openAIApiKeyEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type InstanceSettingsUncheckedUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    openAIApiKey?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    openAIApiKeyEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type InstanceSettingsCreateManyInput = {
    id?: string;
    openAIApiKey?: string | null;
    openAIApiKeyEnabled?: boolean;
    createdAt?: Date | string;
    updatedAt?: Date | string;
};

export type InstanceSettingsUpdateManyMutationInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    openAIApiKey?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    openAIApiKeyEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type InstanceSettingsUncheckedUpdateManyInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    openAIApiKey?:
        | Prisma.NullableStringFieldUpdateOperationsInput
        | string
        | null;
    openAIApiKeyEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type InstanceSettingsCountOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    openAIApiKey?: Prisma.SortOrder;
    openAIApiKeyEnabled?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
};

export type InstanceSettingsMaxOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    openAIApiKey?: Prisma.SortOrder;
    openAIApiKeyEnabled?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
};

export type InstanceSettingsMinOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    openAIApiKey?: Prisma.SortOrder;
    openAIApiKeyEnabled?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
};

export type InstanceSettingsSelect<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        openAIApiKey?: boolean;
        openAIApiKeyEnabled?: boolean;
        createdAt?: boolean;
        updatedAt?: boolean;
    },
    ExtArgs["result"]["instanceSettings"]
>;

export type InstanceSettingsSelectCreateManyAndReturn<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        openAIApiKey?: boolean;
        openAIApiKeyEnabled?: boolean;
        createdAt?: boolean;
        updatedAt?: boolean;
    },
    ExtArgs["result"]["instanceSettings"]
>;

export type InstanceSettingsSelectUpdateManyAndReturn<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        openAIApiKey?: boolean;
        openAIApiKeyEnabled?: boolean;
        createdAt?: boolean;
        updatedAt?: boolean;
    },
    ExtArgs["result"]["instanceSettings"]
>;

export type InstanceSettingsSelectScalar = {
    id?: boolean;
    openAIApiKey?: boolean;
    openAIApiKeyEnabled?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
};

export type InstanceSettingsOmit<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
    "id" | "openAIApiKey" | "openAIApiKeyEnabled" | "createdAt" | "updatedAt",
    ExtArgs["result"]["instanceSettings"]
>;

export type $InstanceSettingsPayload<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    name: "InstanceSettings";
    objects: {};
    scalars: runtime.Types.Extensions.GetPayloadResult<
        {
            id: string;
            openAIApiKey: string | null;
            openAIApiKeyEnabled: boolean;
            createdAt: Date;
            updatedAt: Date;
        },
        ExtArgs["result"]["instanceSettings"]
    >;
    composites: {};
};

export type InstanceSettingsGetPayload<
    S extends boolean | null | undefined | InstanceSettingsDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$InstanceSettingsPayload, S>;

export type InstanceSettingsCountArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<
    InstanceSettingsFindManyArgs,
    "select" | "include" | "distinct" | "omit"
> & {
    select?: InstanceSettingsCountAggregateInputType | true;
};

export interface InstanceSettingsDelegate<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> {
    [K: symbol]: {
        types: Prisma.TypeMap<ExtArgs>["model"]["InstanceSettings"];
        meta: { name: "InstanceSettings" };
    };
    /**
     * Find zero or one InstanceSettings that matches the filter.
     * @param {InstanceSettingsFindUniqueArgs} args - Arguments to find a InstanceSettings
     * @example
     * // Get one InstanceSettings
     * const instanceSettings = await prisma.instanceSettings.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends InstanceSettingsFindUniqueArgs>(
        args: Prisma.SelectSubset<T, InstanceSettingsFindUniqueArgs<ExtArgs>>,
    ): Prisma.Prisma__InstanceSettingsClient<
        runtime.Types.Result.GetResult<
            Prisma.$InstanceSettingsPayload<ExtArgs>,
            T,
            "findUnique",
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find one InstanceSettings that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {InstanceSettingsFindUniqueOrThrowArgs} args - Arguments to find a InstanceSettings
     * @example
     * // Get one InstanceSettings
     * const instanceSettings = await prisma.instanceSettings.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends InstanceSettingsFindUniqueOrThrowArgs>(
        args: Prisma.SelectSubset<
            T,
            InstanceSettingsFindUniqueOrThrowArgs<ExtArgs>
        >,
    ): Prisma.Prisma__InstanceSettingsClient<
        runtime.Types.Result.GetResult<
            Prisma.$InstanceSettingsPayload<ExtArgs>,
            T,
            "findUniqueOrThrow",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first InstanceSettings that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {InstanceSettingsFindFirstArgs} args - Arguments to find a InstanceSettings
     * @example
     * // Get one InstanceSettings
     * const instanceSettings = await prisma.instanceSettings.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends InstanceSettingsFindFirstArgs>(
        args?: Prisma.SelectSubset<T, InstanceSettingsFindFirstArgs<ExtArgs>>,
    ): Prisma.Prisma__InstanceSettingsClient<
        runtime.Types.Result.GetResult<
            Prisma.$InstanceSettingsPayload<ExtArgs>,
            T,
            "findFirst",
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first InstanceSettings that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {InstanceSettingsFindFirstOrThrowArgs} args - Arguments to find a InstanceSettings
     * @example
     * // Get one InstanceSettings
     * const instanceSettings = await prisma.instanceSettings.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends InstanceSettingsFindFirstOrThrowArgs>(
        args?: Prisma.SelectSubset<
            T,
            InstanceSettingsFindFirstOrThrowArgs<ExtArgs>
        >,
    ): Prisma.Prisma__InstanceSettingsClient<
        runtime.Types.Result.GetResult<
            Prisma.$InstanceSettingsPayload<ExtArgs>,
            T,
            "findFirstOrThrow",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find zero or more InstanceSettings that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {InstanceSettingsFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all InstanceSettings
     * const instanceSettings = await prisma.instanceSettings.findMany()
     *
     * // Get first 10 InstanceSettings
     * const instanceSettings = await prisma.instanceSettings.findMany({ take: 10 })
     *
     * // Only select the `id`
     * const instanceSettingsWithIdOnly = await prisma.instanceSettings.findMany({ select: { id: true } })
     *
     */
    findMany<T extends InstanceSettingsFindManyArgs>(
        args?: Prisma.SelectSubset<T, InstanceSettingsFindManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$InstanceSettingsPayload<ExtArgs>,
            T,
            "findMany",
            GlobalOmitOptions
        >
    >;

    /**
     * Create a InstanceSettings.
     * @param {InstanceSettingsCreateArgs} args - Arguments to create a InstanceSettings.
     * @example
     * // Create one InstanceSettings
     * const InstanceSettings = await prisma.instanceSettings.create({
     *   data: {
     *     // ... data to create a InstanceSettings
     *   }
     * })
     *
     */
    create<T extends InstanceSettingsCreateArgs>(
        args: Prisma.SelectSubset<T, InstanceSettingsCreateArgs<ExtArgs>>,
    ): Prisma.Prisma__InstanceSettingsClient<
        runtime.Types.Result.GetResult<
            Prisma.$InstanceSettingsPayload<ExtArgs>,
            T,
            "create",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Create many InstanceSettings.
     * @param {InstanceSettingsCreateManyArgs} args - Arguments to create many InstanceSettings.
     * @example
     * // Create many InstanceSettings
     * const instanceSettings = await prisma.instanceSettings.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     */
    createMany<T extends InstanceSettingsCreateManyArgs>(
        args?: Prisma.SelectSubset<T, InstanceSettingsCreateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Create many InstanceSettings and returns the data saved in the database.
     * @param {InstanceSettingsCreateManyAndReturnArgs} args - Arguments to create many InstanceSettings.
     * @example
     * // Create many InstanceSettings
     * const instanceSettings = await prisma.instanceSettings.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many InstanceSettings and only return the `id`
     * const instanceSettingsWithIdOnly = await prisma.instanceSettings.createManyAndReturn({
     *   select: { id: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    createManyAndReturn<T extends InstanceSettingsCreateManyAndReturnArgs>(
        args?: Prisma.SelectSubset<
            T,
            InstanceSettingsCreateManyAndReturnArgs<ExtArgs>
        >,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$InstanceSettingsPayload<ExtArgs>,
            T,
            "createManyAndReturn",
            GlobalOmitOptions
        >
    >;

    /**
     * Delete a InstanceSettings.
     * @param {InstanceSettingsDeleteArgs} args - Arguments to delete one InstanceSettings.
     * @example
     * // Delete one InstanceSettings
     * const InstanceSettings = await prisma.instanceSettings.delete({
     *   where: {
     *     // ... filter to delete one InstanceSettings
     *   }
     * })
     *
     */
    delete<T extends InstanceSettingsDeleteArgs>(
        args: Prisma.SelectSubset<T, InstanceSettingsDeleteArgs<ExtArgs>>,
    ): Prisma.Prisma__InstanceSettingsClient<
        runtime.Types.Result.GetResult<
            Prisma.$InstanceSettingsPayload<ExtArgs>,
            T,
            "delete",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Update one InstanceSettings.
     * @param {InstanceSettingsUpdateArgs} args - Arguments to update one InstanceSettings.
     * @example
     * // Update one InstanceSettings
     * const instanceSettings = await prisma.instanceSettings.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    update<T extends InstanceSettingsUpdateArgs>(
        args: Prisma.SelectSubset<T, InstanceSettingsUpdateArgs<ExtArgs>>,
    ): Prisma.Prisma__InstanceSettingsClient<
        runtime.Types.Result.GetResult<
            Prisma.$InstanceSettingsPayload<ExtArgs>,
            T,
            "update",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Delete zero or more InstanceSettings.
     * @param {InstanceSettingsDeleteManyArgs} args - Arguments to filter InstanceSettings to delete.
     * @example
     * // Delete a few InstanceSettings
     * const { count } = await prisma.instanceSettings.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     *
     */
    deleteMany<T extends InstanceSettingsDeleteManyArgs>(
        args?: Prisma.SelectSubset<T, InstanceSettingsDeleteManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more InstanceSettings.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {InstanceSettingsUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many InstanceSettings
     * const instanceSettings = await prisma.instanceSettings.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    updateMany<T extends InstanceSettingsUpdateManyArgs>(
        args: Prisma.SelectSubset<T, InstanceSettingsUpdateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more InstanceSettings and returns the data updated in the database.
     * @param {InstanceSettingsUpdateManyAndReturnArgs} args - Arguments to update many InstanceSettings.
     * @example
     * // Update many InstanceSettings
     * const instanceSettings = await prisma.instanceSettings.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more InstanceSettings and only return the `id`
     * const instanceSettingsWithIdOnly = await prisma.instanceSettings.updateManyAndReturn({
     *   select: { id: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    updateManyAndReturn<T extends InstanceSettingsUpdateManyAndReturnArgs>(
        args: Prisma.SelectSubset<
            T,
            InstanceSettingsUpdateManyAndReturnArgs<ExtArgs>
        >,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$InstanceSettingsPayload<ExtArgs>,
            T,
            "updateManyAndReturn",
            GlobalOmitOptions
        >
    >;

    /**
     * Create or update one InstanceSettings.
     * @param {InstanceSettingsUpsertArgs} args - Arguments to update or create a InstanceSettings.
     * @example
     * // Update or create a InstanceSettings
     * const instanceSettings = await prisma.instanceSettings.upsert({
     *   create: {
     *     // ... data to create a InstanceSettings
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the InstanceSettings we want to update
     *   }
     * })
     */
    upsert<T extends InstanceSettingsUpsertArgs>(
        args: Prisma.SelectSubset<T, InstanceSettingsUpsertArgs<ExtArgs>>,
    ): Prisma.Prisma__InstanceSettingsClient<
        runtime.Types.Result.GetResult<
            Prisma.$InstanceSettingsPayload<ExtArgs>,
            T,
            "upsert",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Count the number of InstanceSettings.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {InstanceSettingsCountArgs} args - Arguments to filter InstanceSettings to count.
     * @example
     * // Count the number of InstanceSettings
     * const count = await prisma.instanceSettings.count({
     *   where: {
     *     // ... the filter for the InstanceSettings we want to count
     *   }
     * })
     **/
    count<T extends InstanceSettingsCountArgs>(
        args?: Prisma.Subset<T, InstanceSettingsCountArgs>,
    ): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<"select", any>
            ? T["select"] extends true
                ? number
                : Prisma.GetScalarType<
                      T["select"],
                      InstanceSettingsCountAggregateOutputType
                  >
            : number
    >;

    /**
     * Allows you to perform aggregations operations on a InstanceSettings.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {InstanceSettingsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     **/
    aggregate<T extends InstanceSettingsAggregateArgs>(
        args: Prisma.Subset<T, InstanceSettingsAggregateArgs>,
    ): Prisma.PrismaPromise<GetInstanceSettingsAggregateType<T>>;

    /**
     * Group by InstanceSettings.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {InstanceSettingsGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     *
     **/
    groupBy<
        T extends InstanceSettingsGroupByArgs,
        HasSelectOrTake extends Prisma.Or<
            Prisma.Extends<"skip", Prisma.Keys<T>>,
            Prisma.Extends<"take", Prisma.Keys<T>>
        >,
        OrderByArg extends Prisma.True extends HasSelectOrTake
            ? { orderBy: InstanceSettingsGroupByArgs["orderBy"] }
            : { orderBy?: InstanceSettingsGroupByArgs["orderBy"] },
        OrderFields extends Prisma.ExcludeUnderscoreKeys<
            Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
        >,
        ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
        ByValid extends Prisma.Has<ByFields, OrderFields>,
        HavingFields extends Prisma.GetHavingFields<T["having"]>,
        HavingValid extends Prisma.Has<ByFields, HavingFields>,
        ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
        InputErrors extends ByEmpty extends Prisma.True
            ? `Error: "by" must not be empty.`
            : HavingValid extends Prisma.False
              ? {
                    [P in HavingFields]: P extends ByFields
                        ? never
                        : P extends string
                          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                          : [
                                Error,
                                "Field ",
                                P,
                                ` in "having" needs to be provided in "by"`,
                            ];
                }[HavingFields]
              : "take" extends Prisma.Keys<T>
                ? "orderBy" extends Prisma.Keys<T>
                    ? ByValid extends Prisma.True
                        ? {}
                        : {
                              [P in OrderFields]: P extends ByFields
                                  ? never
                                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                          }[OrderFields]
                    : 'Error: If you provide "take", you also need to provide "orderBy"'
                : "skip" extends Prisma.Keys<T>
                  ? "orderBy" extends Prisma.Keys<T>
                      ? ByValid extends Prisma.True
                          ? {}
                          : {
                                [P in OrderFields]: P extends ByFields
                                    ? never
                                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                            }[OrderFields]
                      : 'Error: If you provide "skip", you also need to provide "orderBy"'
                  : ByValid extends Prisma.True
                    ? {}
                    : {
                          [P in OrderFields]: P extends ByFields
                              ? never
                              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                      }[OrderFields],
    >(
        args: Prisma.SubsetIntersection<
            T,
            InstanceSettingsGroupByArgs,
            OrderByArg
        > &
            InputErrors,
    ): {} extends InputErrors
        ? GetInstanceSettingsGroupByPayload<T>
        : Prisma.PrismaPromise<InputErrors>;
    /**
     * Fields of the InstanceSettings model
     */
    readonly fields: InstanceSettingsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for InstanceSettings.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InstanceSettingsClient<
    T,
    Null = never,
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: "PrismaPromise";
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(
        onfulfilled?:
            | ((value: T) => TResult1 | PromiseLike<TResult1>)
            | undefined
            | null,
        onrejected?:
            | ((reason: any) => TResult2 | PromiseLike<TResult2>)
            | undefined
            | null,
    ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(
        onrejected?:
            | ((reason: any) => TResult | PromiseLike<TResult>)
            | undefined
            | null,
    ): runtime.Types.Utils.JsPromise<T | TResult>;
    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(
        onfinally?: (() => void) | undefined | null,
    ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the InstanceSettings model
 */
export interface InstanceSettingsFieldRefs {
    readonly id: Prisma.FieldRef<"InstanceSettings", "String">;
    readonly openAIApiKey: Prisma.FieldRef<"InstanceSettings", "String">;
    readonly openAIApiKeyEnabled: Prisma.FieldRef<
        "InstanceSettings",
        "Boolean"
    >;
    readonly createdAt: Prisma.FieldRef<"InstanceSettings", "DateTime">;
    readonly updatedAt: Prisma.FieldRef<"InstanceSettings", "DateTime">;
}

// Custom InputTypes
/**
 * InstanceSettings findUnique
 */
export type InstanceSettingsFindUniqueArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the InstanceSettings
     */
    select?: Prisma.InstanceSettingsSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the InstanceSettings
     */
    omit?: Prisma.InstanceSettingsOmit<ExtArgs> | null;
    /**
     * Filter, which InstanceSettings to fetch.
     */
    where: Prisma.InstanceSettingsWhereUniqueInput;
};

/**
 * InstanceSettings findUniqueOrThrow
 */
export type InstanceSettingsFindUniqueOrThrowArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the InstanceSettings
     */
    select?: Prisma.InstanceSettingsSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the InstanceSettings
     */
    omit?: Prisma.InstanceSettingsOmit<ExtArgs> | null;
    /**
     * Filter, which InstanceSettings to fetch.
     */
    where: Prisma.InstanceSettingsWhereUniqueInput;
};

/**
 * InstanceSettings findFirst
 */
export type InstanceSettingsFindFirstArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the InstanceSettings
     */
    select?: Prisma.InstanceSettingsSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the InstanceSettings
     */
    omit?: Prisma.InstanceSettingsOmit<ExtArgs> | null;
    /**
     * Filter, which InstanceSettings to fetch.
     */
    where?: Prisma.InstanceSettingsWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of InstanceSettings to fetch.
     */
    orderBy?:
        | Prisma.InstanceSettingsOrderByWithRelationInput
        | Prisma.InstanceSettingsOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for InstanceSettings.
     */
    cursor?: Prisma.InstanceSettingsWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` InstanceSettings from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` InstanceSettings.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of InstanceSettings.
     */
    distinct?:
        | Prisma.InstanceSettingsScalarFieldEnum
        | Prisma.InstanceSettingsScalarFieldEnum[];
};

/**
 * InstanceSettings findFirstOrThrow
 */
export type InstanceSettingsFindFirstOrThrowArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the InstanceSettings
     */
    select?: Prisma.InstanceSettingsSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the InstanceSettings
     */
    omit?: Prisma.InstanceSettingsOmit<ExtArgs> | null;
    /**
     * Filter, which InstanceSettings to fetch.
     */
    where?: Prisma.InstanceSettingsWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of InstanceSettings to fetch.
     */
    orderBy?:
        | Prisma.InstanceSettingsOrderByWithRelationInput
        | Prisma.InstanceSettingsOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for InstanceSettings.
     */
    cursor?: Prisma.InstanceSettingsWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` InstanceSettings from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` InstanceSettings.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of InstanceSettings.
     */
    distinct?:
        | Prisma.InstanceSettingsScalarFieldEnum
        | Prisma.InstanceSettingsScalarFieldEnum[];
};

/**
 * InstanceSettings findMany
 */
export type InstanceSettingsFindManyArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the InstanceSettings
     */
    select?: Prisma.InstanceSettingsSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the InstanceSettings
     */
    omit?: Prisma.InstanceSettingsOmit<ExtArgs> | null;
    /**
     * Filter, which InstanceSettings to fetch.
     */
    where?: Prisma.InstanceSettingsWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of InstanceSettings to fetch.
     */
    orderBy?:
        | Prisma.InstanceSettingsOrderByWithRelationInput
        | Prisma.InstanceSettingsOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for listing InstanceSettings.
     */
    cursor?: Prisma.InstanceSettingsWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` InstanceSettings from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` InstanceSettings.
     */
    skip?: number;
    distinct?:
        | Prisma.InstanceSettingsScalarFieldEnum
        | Prisma.InstanceSettingsScalarFieldEnum[];
};

/**
 * InstanceSettings create
 */
export type InstanceSettingsCreateArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the InstanceSettings
     */
    select?: Prisma.InstanceSettingsSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the InstanceSettings
     */
    omit?: Prisma.InstanceSettingsOmit<ExtArgs> | null;
    /**
     * The data needed to create a InstanceSettings.
     */
    data: Prisma.XOR<
        Prisma.InstanceSettingsCreateInput,
        Prisma.InstanceSettingsUncheckedCreateInput
    >;
};

/**
 * InstanceSettings createMany
 */
export type InstanceSettingsCreateManyArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to create many InstanceSettings.
     */
    data:
        | Prisma.InstanceSettingsCreateManyInput
        | Prisma.InstanceSettingsCreateManyInput[];
    skipDuplicates?: boolean;
};

/**
 * InstanceSettings createManyAndReturn
 */
export type InstanceSettingsCreateManyAndReturnArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the InstanceSettings
     */
    select?: Prisma.InstanceSettingsSelectCreateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the InstanceSettings
     */
    omit?: Prisma.InstanceSettingsOmit<ExtArgs> | null;
    /**
     * The data used to create many InstanceSettings.
     */
    data:
        | Prisma.InstanceSettingsCreateManyInput
        | Prisma.InstanceSettingsCreateManyInput[];
    skipDuplicates?: boolean;
};

/**
 * InstanceSettings update
 */
export type InstanceSettingsUpdateArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the InstanceSettings
     */
    select?: Prisma.InstanceSettingsSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the InstanceSettings
     */
    omit?: Prisma.InstanceSettingsOmit<ExtArgs> | null;
    /**
     * The data needed to update a InstanceSettings.
     */
    data: Prisma.XOR<
        Prisma.InstanceSettingsUpdateInput,
        Prisma.InstanceSettingsUncheckedUpdateInput
    >;
    /**
     * Choose, which InstanceSettings to update.
     */
    where: Prisma.InstanceSettingsWhereUniqueInput;
};

/**
 * InstanceSettings updateMany
 */
export type InstanceSettingsUpdateManyArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to update InstanceSettings.
     */
    data: Prisma.XOR<
        Prisma.InstanceSettingsUpdateManyMutationInput,
        Prisma.InstanceSettingsUncheckedUpdateManyInput
    >;
    /**
     * Filter which InstanceSettings to update
     */
    where?: Prisma.InstanceSettingsWhereInput;
    /**
     * Limit how many InstanceSettings to update.
     */
    limit?: number;
};

/**
 * InstanceSettings updateManyAndReturn
 */
export type InstanceSettingsUpdateManyAndReturnArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the InstanceSettings
     */
    select?: Prisma.InstanceSettingsSelectUpdateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the InstanceSettings
     */
    omit?: Prisma.InstanceSettingsOmit<ExtArgs> | null;
    /**
     * The data used to update InstanceSettings.
     */
    data: Prisma.XOR<
        Prisma.InstanceSettingsUpdateManyMutationInput,
        Prisma.InstanceSettingsUncheckedUpdateManyInput
    >;
    /**
     * Filter which InstanceSettings to update
     */
    where?: Prisma.InstanceSettingsWhereInput;
    /**
     * Limit how many InstanceSettings to update.
     */
    limit?: number;
};

/**
 * InstanceSettings upsert
 */
export type InstanceSettingsUpsertArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the InstanceSettings
     */
    select?: Prisma.InstanceSettingsSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the InstanceSettings
     */
    omit?: Prisma.InstanceSettingsOmit<ExtArgs> | null;
    /**
     * The filter to search for the InstanceSettings to update in case it exists.
     */
    where: Prisma.InstanceSettingsWhereUniqueInput;
    /**
     * In case the InstanceSettings found by the `where` argument doesn't exist, create a new InstanceSettings with this data.
     */
    create: Prisma.XOR<
        Prisma.InstanceSettingsCreateInput,
        Prisma.InstanceSettingsUncheckedCreateInput
    >;
    /**
     * In case the InstanceSettings was found with the provided `where` argument, update it with this data.
     */
    update: Prisma.XOR<
        Prisma.InstanceSettingsUpdateInput,
        Prisma.InstanceSettingsUncheckedUpdateInput
    >;
};

/**
 * InstanceSettings delete
 */
export type InstanceSettingsDeleteArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the InstanceSettings
     */
    select?: Prisma.InstanceSettingsSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the InstanceSettings
     */
    omit?: Prisma.InstanceSettingsOmit<ExtArgs> | null;
    /**
     * Filter which InstanceSettings to delete.
     */
    where: Prisma.InstanceSettingsWhereUniqueInput;
};

/**
 * InstanceSettings deleteMany
 */
export type InstanceSettingsDeleteManyArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which InstanceSettings to delete
     */
    where?: Prisma.InstanceSettingsWhereInput;
    /**
     * Limit how many InstanceSettings to delete.
     */
    limit?: number;
};

/**
 * InstanceSettings without action
 */
export type InstanceSettingsDefaultArgs<
    ExtArgs extends
        runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the InstanceSettings
     */
    select?: Prisma.InstanceSettingsSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the InstanceSettings
     */
    omit?: Prisma.InstanceSettingsOmit<ExtArgs> | null;
};
