
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `JobResult` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model JobResult
 * 
 */
export type JobResultModel = runtime.Types.Result.DefaultSelection<Prisma.$JobResultPayload>

export type AggregateJobResult = {
  _count: JobResultCountAggregateOutputType | null
  _min: JobResultMinAggregateOutputType | null
  _max: JobResultMaxAggregateOutputType | null
}

export type JobResultMinAggregateOutputType = {
  id: string | null
  jobId: string | null
  status: $Enums.JobResultStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type JobResultMaxAggregateOutputType = {
  id: string | null
  jobId: string | null
  status: $Enums.JobResultStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type JobResultCountAggregateOutputType = {
  id: number
  jobId: number
  status: number
  output: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type JobResultMinAggregateInputType = {
  id?: true
  jobId?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type JobResultMaxAggregateInputType = {
  id?: true
  jobId?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type JobResultCountAggregateInputType = {
  id?: true
  jobId?: true
  status?: true
  output?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type JobResultAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which JobResult to aggregate.
   */
  where?: Prisma.JobResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JobResults to fetch.
   */
  orderBy?: Prisma.JobResultOrderByWithRelationInput | Prisma.JobResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.JobResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JobResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JobResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned JobResults
  **/
  _count?: true | JobResultCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: JobResultMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: JobResultMaxAggregateInputType
}

export type GetJobResultAggregateType<T extends JobResultAggregateArgs> = {
      [P in keyof T & keyof AggregateJobResult]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateJobResult[P]>
    : Prisma.GetScalarType<T[P], AggregateJobResult[P]>
}




export type JobResultGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.JobResultWhereInput
  orderBy?: Prisma.JobResultOrderByWithAggregationInput | Prisma.JobResultOrderByWithAggregationInput[]
  by: Prisma.JobResultScalarFieldEnum[] | Prisma.JobResultScalarFieldEnum
  having?: Prisma.JobResultScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: JobResultCountAggregateInputType | true
  _min?: JobResultMinAggregateInputType
  _max?: JobResultMaxAggregateInputType
}

export type JobResultGroupByOutputType = {
  id: string
  jobId: string
  status: $Enums.JobResultStatus
  output: runtime.JsonValue
  createdAt: Date
  updatedAt: Date
  _count: JobResultCountAggregateOutputType | null
  _min: JobResultMinAggregateOutputType | null
  _max: JobResultMaxAggregateOutputType | null
}

type GetJobResultGroupByPayload<T extends JobResultGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<JobResultGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof JobResultGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], JobResultGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], JobResultGroupByOutputType[P]>
      }
    >
  >



export type JobResultWhereInput = {
  AND?: Prisma.JobResultWhereInput | Prisma.JobResultWhereInput[]
  OR?: Prisma.JobResultWhereInput[]
  NOT?: Prisma.JobResultWhereInput | Prisma.JobResultWhereInput[]
  id?: Prisma.StringFilter<"JobResult"> | string
  jobId?: Prisma.StringFilter<"JobResult"> | string
  status?: Prisma.EnumJobResultStatusFilter<"JobResult"> | $Enums.JobResultStatus
  output?: Prisma.JsonFilter<"JobResult">
  createdAt?: Prisma.DateTimeFilter<"JobResult"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"JobResult"> | Date | string
  job?: Prisma.XOR<Prisma.JobScalarRelationFilter, Prisma.JobWhereInput>
}

export type JobResultOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  jobId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  output?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  job?: Prisma.JobOrderByWithRelationInput
}

export type JobResultWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  jobId?: string
  AND?: Prisma.JobResultWhereInput | Prisma.JobResultWhereInput[]
  OR?: Prisma.JobResultWhereInput[]
  NOT?: Prisma.JobResultWhereInput | Prisma.JobResultWhereInput[]
  status?: Prisma.EnumJobResultStatusFilter<"JobResult"> | $Enums.JobResultStatus
  output?: Prisma.JsonFilter<"JobResult">
  createdAt?: Prisma.DateTimeFilter<"JobResult"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"JobResult"> | Date | string
  job?: Prisma.XOR<Prisma.JobScalarRelationFilter, Prisma.JobWhereInput>
}, "id" | "jobId">

export type JobResultOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  jobId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  output?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.JobResultCountOrderByAggregateInput
  _max?: Prisma.JobResultMaxOrderByAggregateInput
  _min?: Prisma.JobResultMinOrderByAggregateInput
}

export type JobResultScalarWhereWithAggregatesInput = {
  AND?: Prisma.JobResultScalarWhereWithAggregatesInput | Prisma.JobResultScalarWhereWithAggregatesInput[]
  OR?: Prisma.JobResultScalarWhereWithAggregatesInput[]
  NOT?: Prisma.JobResultScalarWhereWithAggregatesInput | Prisma.JobResultScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"JobResult"> | string
  jobId?: Prisma.StringWithAggregatesFilter<"JobResult"> | string
  status?: Prisma.EnumJobResultStatusWithAggregatesFilter<"JobResult"> | $Enums.JobResultStatus
  output?: Prisma.JsonWithAggregatesFilter<"JobResult">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"JobResult"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"JobResult"> | Date | string
}

export type JobResultCreateInput = {
  id?: string
  status: $Enums.JobResultStatus
  output: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  job: Prisma.JobCreateNestedOneWithoutResultInput
}

export type JobResultUncheckedCreateInput = {
  id?: string
  jobId: string
  status: $Enums.JobResultStatus
  output: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type JobResultUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumJobResultStatusFieldUpdateOperationsInput | $Enums.JobResultStatus
  output?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  job?: Prisma.JobUpdateOneRequiredWithoutResultNestedInput
}

export type JobResultUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  jobId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumJobResultStatusFieldUpdateOperationsInput | $Enums.JobResultStatus
  output?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JobResultCreateManyInput = {
  id?: string
  jobId: string
  status: $Enums.JobResultStatus
  output: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type JobResultUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumJobResultStatusFieldUpdateOperationsInput | $Enums.JobResultStatus
  output?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JobResultUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  jobId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumJobResultStatusFieldUpdateOperationsInput | $Enums.JobResultStatus
  output?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JobResultNullableScalarRelationFilter = {
  is?: Prisma.JobResultWhereInput | null
  isNot?: Prisma.JobResultWhereInput | null
}

export type JobResultCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  jobId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  output?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type JobResultMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  jobId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type JobResultMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  jobId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type JobResultCreateNestedOneWithoutJobInput = {
  create?: Prisma.XOR<Prisma.JobResultCreateWithoutJobInput, Prisma.JobResultUncheckedCreateWithoutJobInput>
  connectOrCreate?: Prisma.JobResultCreateOrConnectWithoutJobInput
  connect?: Prisma.JobResultWhereUniqueInput
}

export type JobResultUncheckedCreateNestedOneWithoutJobInput = {
  create?: Prisma.XOR<Prisma.JobResultCreateWithoutJobInput, Prisma.JobResultUncheckedCreateWithoutJobInput>
  connectOrCreate?: Prisma.JobResultCreateOrConnectWithoutJobInput
  connect?: Prisma.JobResultWhereUniqueInput
}

export type JobResultUpdateOneWithoutJobNestedInput = {
  create?: Prisma.XOR<Prisma.JobResultCreateWithoutJobInput, Prisma.JobResultUncheckedCreateWithoutJobInput>
  connectOrCreate?: Prisma.JobResultCreateOrConnectWithoutJobInput
  upsert?: Prisma.JobResultUpsertWithoutJobInput
  disconnect?: Prisma.JobResultWhereInput | boolean
  delete?: Prisma.JobResultWhereInput | boolean
  connect?: Prisma.JobResultWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.JobResultUpdateToOneWithWhereWithoutJobInput, Prisma.JobResultUpdateWithoutJobInput>, Prisma.JobResultUncheckedUpdateWithoutJobInput>
}

export type JobResultUncheckedUpdateOneWithoutJobNestedInput = {
  create?: Prisma.XOR<Prisma.JobResultCreateWithoutJobInput, Prisma.JobResultUncheckedCreateWithoutJobInput>
  connectOrCreate?: Prisma.JobResultCreateOrConnectWithoutJobInput
  upsert?: Prisma.JobResultUpsertWithoutJobInput
  disconnect?: Prisma.JobResultWhereInput | boolean
  delete?: Prisma.JobResultWhereInput | boolean
  connect?: Prisma.JobResultWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.JobResultUpdateToOneWithWhereWithoutJobInput, Prisma.JobResultUpdateWithoutJobInput>, Prisma.JobResultUncheckedUpdateWithoutJobInput>
}

export type EnumJobResultStatusFieldUpdateOperationsInput = {
  set?: $Enums.JobResultStatus
}

export type JobResultCreateWithoutJobInput = {
  id?: string
  status: $Enums.JobResultStatus
  output: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type JobResultUncheckedCreateWithoutJobInput = {
  id?: string
  status: $Enums.JobResultStatus
  output: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type JobResultCreateOrConnectWithoutJobInput = {
  where: Prisma.JobResultWhereUniqueInput
  create: Prisma.XOR<Prisma.JobResultCreateWithoutJobInput, Prisma.JobResultUncheckedCreateWithoutJobInput>
}

export type JobResultUpsertWithoutJobInput = {
  update: Prisma.XOR<Prisma.JobResultUpdateWithoutJobInput, Prisma.JobResultUncheckedUpdateWithoutJobInput>
  create: Prisma.XOR<Prisma.JobResultCreateWithoutJobInput, Prisma.JobResultUncheckedCreateWithoutJobInput>
  where?: Prisma.JobResultWhereInput
}

export type JobResultUpdateToOneWithWhereWithoutJobInput = {
  where?: Prisma.JobResultWhereInput
  data: Prisma.XOR<Prisma.JobResultUpdateWithoutJobInput, Prisma.JobResultUncheckedUpdateWithoutJobInput>
}

export type JobResultUpdateWithoutJobInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumJobResultStatusFieldUpdateOperationsInput | $Enums.JobResultStatus
  output?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JobResultUncheckedUpdateWithoutJobInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumJobResultStatusFieldUpdateOperationsInput | $Enums.JobResultStatus
  output?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type JobResultSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  jobId?: boolean
  status?: boolean
  output?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  job?: boolean | Prisma.JobDefaultArgs<ExtArgs>
}, ExtArgs["result"]["jobResult"]>

export type JobResultSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  jobId?: boolean
  status?: boolean
  output?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  job?: boolean | Prisma.JobDefaultArgs<ExtArgs>
}, ExtArgs["result"]["jobResult"]>

export type JobResultSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  jobId?: boolean
  status?: boolean
  output?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  job?: boolean | Prisma.JobDefaultArgs<ExtArgs>
}, ExtArgs["result"]["jobResult"]>

export type JobResultSelectScalar = {
  id?: boolean
  jobId?: boolean
  status?: boolean
  output?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type JobResultOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "jobId" | "status" | "output" | "createdAt" | "updatedAt", ExtArgs["result"]["jobResult"]>
export type JobResultInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  job?: boolean | Prisma.JobDefaultArgs<ExtArgs>
}
export type JobResultIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  job?: boolean | Prisma.JobDefaultArgs<ExtArgs>
}
export type JobResultIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  job?: boolean | Prisma.JobDefaultArgs<ExtArgs>
}

export type $JobResultPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "JobResult"
  objects: {
    job: Prisma.$JobPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    jobId: string
    status: $Enums.JobResultStatus
    output: runtime.JsonValue
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["jobResult"]>
  composites: {}
}

export type JobResultGetPayload<S extends boolean | null | undefined | JobResultDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$JobResultPayload, S>

export type JobResultCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<JobResultFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: JobResultCountAggregateInputType | true
  }

export interface JobResultDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['JobResult'], meta: { name: 'JobResult' } }
  /**
   * Find zero or one JobResult that matches the filter.
   * @param {JobResultFindUniqueArgs} args - Arguments to find a JobResult
   * @example
   * // Get one JobResult
   * const jobResult = await prisma.jobResult.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends JobResultFindUniqueArgs>(args: Prisma.SelectSubset<T, JobResultFindUniqueArgs<ExtArgs>>): Prisma.Prisma__JobResultClient<runtime.Types.Result.GetResult<Prisma.$JobResultPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one JobResult that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {JobResultFindUniqueOrThrowArgs} args - Arguments to find a JobResult
   * @example
   * // Get one JobResult
   * const jobResult = await prisma.jobResult.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends JobResultFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, JobResultFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__JobResultClient<runtime.Types.Result.GetResult<Prisma.$JobResultPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first JobResult that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobResultFindFirstArgs} args - Arguments to find a JobResult
   * @example
   * // Get one JobResult
   * const jobResult = await prisma.jobResult.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends JobResultFindFirstArgs>(args?: Prisma.SelectSubset<T, JobResultFindFirstArgs<ExtArgs>>): Prisma.Prisma__JobResultClient<runtime.Types.Result.GetResult<Prisma.$JobResultPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first JobResult that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobResultFindFirstOrThrowArgs} args - Arguments to find a JobResult
   * @example
   * // Get one JobResult
   * const jobResult = await prisma.jobResult.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends JobResultFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, JobResultFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__JobResultClient<runtime.Types.Result.GetResult<Prisma.$JobResultPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more JobResults that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobResultFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all JobResults
   * const jobResults = await prisma.jobResult.findMany()
   * 
   * // Get first 10 JobResults
   * const jobResults = await prisma.jobResult.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const jobResultWithIdOnly = await prisma.jobResult.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends JobResultFindManyArgs>(args?: Prisma.SelectSubset<T, JobResultFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JobResultPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a JobResult.
   * @param {JobResultCreateArgs} args - Arguments to create a JobResult.
   * @example
   * // Create one JobResult
   * const JobResult = await prisma.jobResult.create({
   *   data: {
   *     // ... data to create a JobResult
   *   }
   * })
   * 
   */
  create<T extends JobResultCreateArgs>(args: Prisma.SelectSubset<T, JobResultCreateArgs<ExtArgs>>): Prisma.Prisma__JobResultClient<runtime.Types.Result.GetResult<Prisma.$JobResultPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many JobResults.
   * @param {JobResultCreateManyArgs} args - Arguments to create many JobResults.
   * @example
   * // Create many JobResults
   * const jobResult = await prisma.jobResult.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends JobResultCreateManyArgs>(args?: Prisma.SelectSubset<T, JobResultCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many JobResults and returns the data saved in the database.
   * @param {JobResultCreateManyAndReturnArgs} args - Arguments to create many JobResults.
   * @example
   * // Create many JobResults
   * const jobResult = await prisma.jobResult.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many JobResults and only return the `id`
   * const jobResultWithIdOnly = await prisma.jobResult.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends JobResultCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, JobResultCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JobResultPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a JobResult.
   * @param {JobResultDeleteArgs} args - Arguments to delete one JobResult.
   * @example
   * // Delete one JobResult
   * const JobResult = await prisma.jobResult.delete({
   *   where: {
   *     // ... filter to delete one JobResult
   *   }
   * })
   * 
   */
  delete<T extends JobResultDeleteArgs>(args: Prisma.SelectSubset<T, JobResultDeleteArgs<ExtArgs>>): Prisma.Prisma__JobResultClient<runtime.Types.Result.GetResult<Prisma.$JobResultPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one JobResult.
   * @param {JobResultUpdateArgs} args - Arguments to update one JobResult.
   * @example
   * // Update one JobResult
   * const jobResult = await prisma.jobResult.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends JobResultUpdateArgs>(args: Prisma.SelectSubset<T, JobResultUpdateArgs<ExtArgs>>): Prisma.Prisma__JobResultClient<runtime.Types.Result.GetResult<Prisma.$JobResultPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more JobResults.
   * @param {JobResultDeleteManyArgs} args - Arguments to filter JobResults to delete.
   * @example
   * // Delete a few JobResults
   * const { count } = await prisma.jobResult.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends JobResultDeleteManyArgs>(args?: Prisma.SelectSubset<T, JobResultDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more JobResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobResultUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many JobResults
   * const jobResult = await prisma.jobResult.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends JobResultUpdateManyArgs>(args: Prisma.SelectSubset<T, JobResultUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more JobResults and returns the data updated in the database.
   * @param {JobResultUpdateManyAndReturnArgs} args - Arguments to update many JobResults.
   * @example
   * // Update many JobResults
   * const jobResult = await prisma.jobResult.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more JobResults and only return the `id`
   * const jobResultWithIdOnly = await prisma.jobResult.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends JobResultUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, JobResultUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JobResultPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one JobResult.
   * @param {JobResultUpsertArgs} args - Arguments to update or create a JobResult.
   * @example
   * // Update or create a JobResult
   * const jobResult = await prisma.jobResult.upsert({
   *   create: {
   *     // ... data to create a JobResult
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the JobResult we want to update
   *   }
   * })
   */
  upsert<T extends JobResultUpsertArgs>(args: Prisma.SelectSubset<T, JobResultUpsertArgs<ExtArgs>>): Prisma.Prisma__JobResultClient<runtime.Types.Result.GetResult<Prisma.$JobResultPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of JobResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobResultCountArgs} args - Arguments to filter JobResults to count.
   * @example
   * // Count the number of JobResults
   * const count = await prisma.jobResult.count({
   *   where: {
   *     // ... the filter for the JobResults we want to count
   *   }
   * })
  **/
  count<T extends JobResultCountArgs>(
    args?: Prisma.Subset<T, JobResultCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], JobResultCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a JobResult.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobResultAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends JobResultAggregateArgs>(args: Prisma.Subset<T, JobResultAggregateArgs>): Prisma.PrismaPromise<GetJobResultAggregateType<T>>

  /**
   * Group by JobResult.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobResultGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends JobResultGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: JobResultGroupByArgs['orderBy'] }
      : { orderBy?: JobResultGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, JobResultGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetJobResultGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the JobResult model
 */
readonly fields: JobResultFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for JobResult.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__JobResultClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  job<T extends Prisma.JobDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.JobDefaultArgs<ExtArgs>>): Prisma.Prisma__JobClient<runtime.Types.Result.GetResult<Prisma.$JobPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the JobResult model
 */
export interface JobResultFieldRefs {
  readonly id: Prisma.FieldRef<"JobResult", 'String'>
  readonly jobId: Prisma.FieldRef<"JobResult", 'String'>
  readonly status: Prisma.FieldRef<"JobResult", 'JobResultStatus'>
  readonly output: Prisma.FieldRef<"JobResult", 'Json'>
  readonly createdAt: Prisma.FieldRef<"JobResult", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"JobResult", 'DateTime'>
}
    

// Custom InputTypes
/**
 * JobResult findUnique
 */
export type JobResultFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobResult
   */
  select?: Prisma.JobResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobResult
   */
  omit?: Prisma.JobResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobResultInclude<ExtArgs> | null
  /**
   * Filter, which JobResult to fetch.
   */
  where: Prisma.JobResultWhereUniqueInput
}

/**
 * JobResult findUniqueOrThrow
 */
export type JobResultFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobResult
   */
  select?: Prisma.JobResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobResult
   */
  omit?: Prisma.JobResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobResultInclude<ExtArgs> | null
  /**
   * Filter, which JobResult to fetch.
   */
  where: Prisma.JobResultWhereUniqueInput
}

/**
 * JobResult findFirst
 */
export type JobResultFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobResult
   */
  select?: Prisma.JobResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobResult
   */
  omit?: Prisma.JobResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobResultInclude<ExtArgs> | null
  /**
   * Filter, which JobResult to fetch.
   */
  where?: Prisma.JobResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JobResults to fetch.
   */
  orderBy?: Prisma.JobResultOrderByWithRelationInput | Prisma.JobResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for JobResults.
   */
  cursor?: Prisma.JobResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JobResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JobResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JobResults.
   */
  distinct?: Prisma.JobResultScalarFieldEnum | Prisma.JobResultScalarFieldEnum[]
}

/**
 * JobResult findFirstOrThrow
 */
export type JobResultFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobResult
   */
  select?: Prisma.JobResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobResult
   */
  omit?: Prisma.JobResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobResultInclude<ExtArgs> | null
  /**
   * Filter, which JobResult to fetch.
   */
  where?: Prisma.JobResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JobResults to fetch.
   */
  orderBy?: Prisma.JobResultOrderByWithRelationInput | Prisma.JobResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for JobResults.
   */
  cursor?: Prisma.JobResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JobResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JobResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JobResults.
   */
  distinct?: Prisma.JobResultScalarFieldEnum | Prisma.JobResultScalarFieldEnum[]
}

/**
 * JobResult findMany
 */
export type JobResultFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobResult
   */
  select?: Prisma.JobResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobResult
   */
  omit?: Prisma.JobResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobResultInclude<ExtArgs> | null
  /**
   * Filter, which JobResults to fetch.
   */
  where?: Prisma.JobResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JobResults to fetch.
   */
  orderBy?: Prisma.JobResultOrderByWithRelationInput | Prisma.JobResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing JobResults.
   */
  cursor?: Prisma.JobResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JobResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JobResults.
   */
  skip?: number
  distinct?: Prisma.JobResultScalarFieldEnum | Prisma.JobResultScalarFieldEnum[]
}

/**
 * JobResult create
 */
export type JobResultCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobResult
   */
  select?: Prisma.JobResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobResult
   */
  omit?: Prisma.JobResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobResultInclude<ExtArgs> | null
  /**
   * The data needed to create a JobResult.
   */
  data: Prisma.XOR<Prisma.JobResultCreateInput, Prisma.JobResultUncheckedCreateInput>
}

/**
 * JobResult createMany
 */
export type JobResultCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many JobResults.
   */
  data: Prisma.JobResultCreateManyInput | Prisma.JobResultCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * JobResult createManyAndReturn
 */
export type JobResultCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobResult
   */
  select?: Prisma.JobResultSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the JobResult
   */
  omit?: Prisma.JobResultOmit<ExtArgs> | null
  /**
   * The data used to create many JobResults.
   */
  data: Prisma.JobResultCreateManyInput | Prisma.JobResultCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobResultIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * JobResult update
 */
export type JobResultUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobResult
   */
  select?: Prisma.JobResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobResult
   */
  omit?: Prisma.JobResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobResultInclude<ExtArgs> | null
  /**
   * The data needed to update a JobResult.
   */
  data: Prisma.XOR<Prisma.JobResultUpdateInput, Prisma.JobResultUncheckedUpdateInput>
  /**
   * Choose, which JobResult to update.
   */
  where: Prisma.JobResultWhereUniqueInput
}

/**
 * JobResult updateMany
 */
export type JobResultUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update JobResults.
   */
  data: Prisma.XOR<Prisma.JobResultUpdateManyMutationInput, Prisma.JobResultUncheckedUpdateManyInput>
  /**
   * Filter which JobResults to update
   */
  where?: Prisma.JobResultWhereInput
  /**
   * Limit how many JobResults to update.
   */
  limit?: number
}

/**
 * JobResult updateManyAndReturn
 */
export type JobResultUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobResult
   */
  select?: Prisma.JobResultSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the JobResult
   */
  omit?: Prisma.JobResultOmit<ExtArgs> | null
  /**
   * The data used to update JobResults.
   */
  data: Prisma.XOR<Prisma.JobResultUpdateManyMutationInput, Prisma.JobResultUncheckedUpdateManyInput>
  /**
   * Filter which JobResults to update
   */
  where?: Prisma.JobResultWhereInput
  /**
   * Limit how many JobResults to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobResultIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * JobResult upsert
 */
export type JobResultUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobResult
   */
  select?: Prisma.JobResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobResult
   */
  omit?: Prisma.JobResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobResultInclude<ExtArgs> | null
  /**
   * The filter to search for the JobResult to update in case it exists.
   */
  where: Prisma.JobResultWhereUniqueInput
  /**
   * In case the JobResult found by the `where` argument doesn't exist, create a new JobResult with this data.
   */
  create: Prisma.XOR<Prisma.JobResultCreateInput, Prisma.JobResultUncheckedCreateInput>
  /**
   * In case the JobResult was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.JobResultUpdateInput, Prisma.JobResultUncheckedUpdateInput>
}

/**
 * JobResult delete
 */
export type JobResultDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobResult
   */
  select?: Prisma.JobResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobResult
   */
  omit?: Prisma.JobResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobResultInclude<ExtArgs> | null
  /**
   * Filter which JobResult to delete.
   */
  where: Prisma.JobResultWhereUniqueInput
}

/**
 * JobResult deleteMany
 */
export type JobResultDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which JobResults to delete
   */
  where?: Prisma.JobResultWhereInput
  /**
   * Limit how many JobResults to delete.
   */
  limit?: number
}

/**
 * JobResult without action
 */
export type JobResultDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobResult
   */
  select?: Prisma.JobResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobResult
   */
  omit?: Prisma.JobResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobResultInclude<ExtArgs> | null
}
