name: Setup Frontend

runs:
    using: composite
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v6
          with:
              node-version: "22"
              cache: "npm"
              cache-dependency-path: "apps/frontend/package-lock.json"

        - name: Install dependencies
          run: npm ci
          working-directory: ./apps/frontend
          shell: bash
