/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type {
    ChangeEmail200,
    ChangePassword200,
    DeleteUser200,
    GetAccountInfo200,
    GetDeleteUserCallback200,
    GetOk200,
    GetSession200,
    GetVerifyEmail200,
    LinkSocialAccount200,
    ListUserAccounts200Item,
    PostGetAccessToken200,
    PostRefreshToken200,
    PostRevokeOtherSessions200,
    PostRevokeSession200,
    PostRevokeSessions200,
    PostUnlinkAccount200,
    RequestPasswordReset200,
    ResetPassword200,
    ResetPasswordCallback200,
    SendVerificationEmail200,
    Session,
    SignInEmail200,
    SignOut200,
    SignUpWithEmailAndPassword200,
    SocialSignIn200,
    UpdateUser200,
} from ".././models";

export const getSocialSignInResponseMock = (
    overrideResponse: Partial<SocialSignIn200> = {},
): SocialSignIn200 => ({
    token: faker.string.alpha({ length: { min: 10, max: 20 } }),
    user: {
        id: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        email: faker.string.alpha({ length: { min: 10, max: 20 } }),
        emailVerified: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
        image: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        createdAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        updatedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        role: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
    },
    url: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
    ]),
    redirect: faker.datatype.boolean(),
    ...overrideResponse,
});

export const getGetSessionResponseMock = (
    overrideResponse: Partial<GetSession200> = {},
): GetSession200 => ({
    session: {
        id: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        expiresAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        token: faker.string.alpha({ length: { min: 10, max: 20 } }),
        createdAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        updatedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        ipAddress: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        userAgent: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        userId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    user: {
        id: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        email: faker.string.alpha({ length: { min: 10, max: 20 } }),
        emailVerified: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
        image: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        createdAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        updatedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        role: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
    },
    ...overrideResponse,
});

export const getSignOutResponseMock = (overrideResponse: Partial<SignOut200> = {}): SignOut200 => ({
    success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    ...overrideResponse,
});

export const getSignUpWithEmailAndPasswordResponseMock = (
    overrideResponse: Partial<SignUpWithEmailAndPassword200> = {},
): SignUpWithEmailAndPassword200 => ({
    token: faker.helpers.arrayElement([
        faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
        undefined,
    ]),
    user: {
        id: faker.string.alpha({ length: { min: 10, max: 20 } }),
        email: faker.internet.email(),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        image: faker.helpers.arrayElement([
            faker.helpers.arrayElement([faker.internet.url(), null]),
            undefined,
        ]),
        emailVerified: faker.datatype.boolean(),
        createdAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        updatedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
    },
    ...overrideResponse,
});

export const getSignInEmailResponseMock = (
    overrideResponse: Partial<SignInEmail200> = {},
): SignInEmail200 => ({
    redirect: faker.datatype.boolean(),
    token: faker.string.alpha({ length: { min: 10, max: 20 } }),
    url: faker.helpers.arrayElement([
        faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
        undefined,
    ]),
    user: {
        id: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        email: faker.string.alpha({ length: { min: 10, max: 20 } }),
        emailVerified: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
        image: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        createdAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        updatedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        role: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
    },
    ...overrideResponse,
});

export const getResetPasswordResponseMock = (
    overrideResponse: Partial<ResetPassword200> = {},
): ResetPassword200 => ({
    status: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    ...overrideResponse,
});

export const getGetVerifyEmailResponseMock = (
    overrideResponse: Partial<GetVerifyEmail200> = {},
): GetVerifyEmail200 => ({
    user: {
        id: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        email: faker.string.alpha({ length: { min: 10, max: 20 } }),
        emailVerified: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
        image: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        createdAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        updatedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        role: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
    },
    status: faker.datatype.boolean(),
    ...overrideResponse,
});

export const getSendVerificationEmailResponseMock = (
    overrideResponse: Partial<SendVerificationEmail200> = {},
): SendVerificationEmail200 => ({
    status: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    ...overrideResponse,
});

export const getChangeEmailResponseMock = (
    overrideResponse: Partial<ChangeEmail200> = {},
): ChangeEmail200 => ({
    user: faker.helpers.arrayElement([
        {
            id: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                undefined,
            ]),
            name: faker.string.alpha({ length: { min: 10, max: 20 } }),
            email: faker.string.alpha({ length: { min: 10, max: 20 } }),
            emailVerified: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
            image: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                undefined,
            ]),
            createdAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
            updatedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
            role: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                undefined,
            ]),
        },
        undefined,
    ]),
    status: faker.datatype.boolean(),
    message: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
            faker.helpers.arrayElement(["Email updated", "Verification email sent"] as const),
            null,
        ]),
        undefined,
    ]),
    ...overrideResponse,
});

export const getChangePasswordResponseMock = (
    overrideResponse: Partial<ChangePassword200> = {},
): ChangePassword200 => ({
    token: faker.helpers.arrayElement([
        faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
        undefined,
    ]),
    user: {
        id: faker.string.alpha({ length: { min: 10, max: 20 } }),
        email: faker.internet.email(),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        image: faker.helpers.arrayElement([
            faker.helpers.arrayElement([faker.internet.url(), null]),
            undefined,
        ]),
        emailVerified: faker.datatype.boolean(),
        createdAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        updatedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
    },
    ...overrideResponse,
});

export const getUpdateUserResponseMock = (
    overrideResponse: Partial<UpdateUser200> = {},
): UpdateUser200 => ({
    user: faker.helpers.arrayElement([
        {
            id: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                undefined,
            ]),
            name: faker.string.alpha({ length: { min: 10, max: 20 } }),
            email: faker.string.alpha({ length: { min: 10, max: 20 } }),
            emailVerified: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
            image: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                undefined,
            ]),
            createdAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
            updatedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
            role: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                undefined,
            ]),
        },
        undefined,
    ]),
    ...overrideResponse,
});

export const getDeleteUserResponseMock = (
    overrideResponse: Partial<DeleteUser200> = {},
): DeleteUser200 => ({
    success: faker.datatype.boolean(),
    message: faker.helpers.arrayElement(["User deleted", "Verification email sent"] as const),
    ...overrideResponse,
});

export const getRequestPasswordResetResponseMock = (
    overrideResponse: Partial<RequestPasswordReset200> = {},
): RequestPasswordReset200 => ({
    status: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    message: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
    ]),
    ...overrideResponse,
});

export const getResetPasswordCallbackResponseMock = (
    overrideResponse: Partial<ResetPasswordCallback200> = {},
): ResetPasswordCallback200 => ({
    token: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
    ]),
    ...overrideResponse,
});

export const getListUserSessionsResponseMock = (): Session[] =>
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
        id: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        expiresAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        token: faker.string.alpha({ length: { min: 10, max: 20 } }),
        createdAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        updatedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        ipAddress: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        userAgent: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        userId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    }));

export const getPostRevokeSessionResponseMock = (
    overrideResponse: Partial<PostRevokeSession200> = {},
): PostRevokeSession200 => ({ status: faker.datatype.boolean(), ...overrideResponse });

export const getPostRevokeSessionsResponseMock = (
    overrideResponse: Partial<PostRevokeSessions200> = {},
): PostRevokeSessions200 => ({ status: faker.datatype.boolean(), ...overrideResponse });

export const getPostRevokeOtherSessionsResponseMock = (
    overrideResponse: Partial<PostRevokeOtherSessions200> = {},
): PostRevokeOtherSessions200 => ({ status: faker.datatype.boolean(), ...overrideResponse });

export const getLinkSocialAccountResponseMock = (
    overrideResponse: Partial<LinkSocialAccount200> = {},
): LinkSocialAccount200 => ({
    url: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
    ]),
    redirect: faker.datatype.boolean(),
    status: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    ...overrideResponse,
});

export const getListUserAccountsResponseMock = (): ListUserAccounts200Item[] =>
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
        id: faker.string.alpha({ length: { min: 10, max: 20 } }),
        providerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
        createdAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        updatedAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
        accountId: faker.string.alpha({ length: { min: 10, max: 20 } }),
        userId: faker.string.alpha({ length: { min: 10, max: 20 } }),
        scopes: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
            () => faker.string.alpha({ length: { min: 10, max: 20 } }),
        ),
    }));

export const getGetDeleteUserCallbackResponseMock = (
    overrideResponse: Partial<GetDeleteUserCallback200> = {},
): GetDeleteUserCallback200 => ({
    success: faker.datatype.boolean(),
    message: faker.helpers.arrayElement(["User deleted"] as const),
    ...overrideResponse,
});

export const getPostUnlinkAccountResponseMock = (
    overrideResponse: Partial<PostUnlinkAccount200> = {},
): PostUnlinkAccount200 => ({
    status: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    ...overrideResponse,
});

export const getPostRefreshTokenResponseMock = (
    overrideResponse: Partial<PostRefreshToken200> = {},
): PostRefreshToken200 => ({
    tokenType: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
    ]),
    idToken: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
    ]),
    accessToken: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
    ]),
    refreshToken: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
    ]),
    accessTokenExpiresAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split(".")[0]}Z`,
        undefined,
    ]),
    refreshTokenExpiresAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split(".")[0]}Z`,
        undefined,
    ]),
    ...overrideResponse,
});

export const getPostGetAccessTokenResponseMock = (
    overrideResponse: Partial<PostGetAccessToken200> = {},
): PostGetAccessToken200 => ({
    tokenType: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
    ]),
    idToken: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
    ]),
    accessToken: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
    ]),
    refreshToken: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
    ]),
    accessTokenExpiresAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split(".")[0]}Z`,
        undefined,
    ]),
    refreshTokenExpiresAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split(".")[0]}Z`,
        undefined,
    ]),
    ...overrideResponse,
});

export const getGetAccountInfoResponseMock = (
    overrideResponse: Partial<GetAccountInfo200> = {},
): GetAccountInfo200 => ({
    user: {
        id: faker.string.alpha({ length: { min: 10, max: 20 } }),
        name: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        email: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        image: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
        ]),
        emailVerified: faker.datatype.boolean(),
    },
    data: {},
    ...overrideResponse,
});

export const getGetOkResponseMock = (overrideResponse: Partial<GetOk200> = {}): GetOk200 => ({
    ok: faker.datatype.boolean(),
    ...overrideResponse,
});

export const getGetErrorResponseMock = (): string => faker.word.sample();

export const getSocialSignInMockHandler = (
    overrideResponse?:
        | SocialSignIn200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<SocialSignIn200> | SocialSignIn200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/sign-in/social",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getSocialSignInResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getGetSessionMockHandler = (
    overrideResponse?:
        | GetSession200
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0],
          ) => Promise<GetSession200> | GetSession200),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        "*/get-session",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetSessionResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getSignOutMockHandler = (
    overrideResponse?:
        | SignOut200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<SignOut200> | SignOut200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/sign-out",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getSignOutResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getSignUpWithEmailAndPasswordMockHandler = (
    overrideResponse?:
        | SignUpWithEmailAndPassword200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<SignUpWithEmailAndPassword200> | SignUpWithEmailAndPassword200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/sign-up/email",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getSignUpWithEmailAndPasswordResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getSignInEmailMockHandler = (
    overrideResponse?:
        | SignInEmail200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<SignInEmail200> | SignInEmail200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/sign-in/email",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getSignInEmailResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getResetPasswordMockHandler = (
    overrideResponse?:
        | ResetPassword200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<ResetPassword200> | ResetPassword200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/reset-password",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getResetPasswordResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getGetVerifyEmailMockHandler = (
    overrideResponse?:
        | GetVerifyEmail200
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0],
          ) => Promise<GetVerifyEmail200> | GetVerifyEmail200),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        "*/verify-email",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetVerifyEmailResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getSendVerificationEmailMockHandler = (
    overrideResponse?:
        | SendVerificationEmail200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<SendVerificationEmail200> | SendVerificationEmail200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/send-verification-email",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getSendVerificationEmailResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getChangeEmailMockHandler = (
    overrideResponse?:
        | ChangeEmail200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<ChangeEmail200> | ChangeEmail200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/change-email",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getChangeEmailResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getChangePasswordMockHandler = (
    overrideResponse?:
        | ChangePassword200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<ChangePassword200> | ChangePassword200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/change-password",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getChangePasswordResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getUpdateUserMockHandler = (
    overrideResponse?:
        | UpdateUser200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<UpdateUser200> | UpdateUser200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/update-user",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getUpdateUserResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getDeleteUserMockHandler = (
    overrideResponse?:
        | DeleteUser200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<DeleteUser200> | DeleteUser200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/delete-user",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getDeleteUserResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getRequestPasswordResetMockHandler = (
    overrideResponse?:
        | RequestPasswordReset200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<RequestPasswordReset200> | RequestPasswordReset200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/request-password-reset",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getRequestPasswordResetResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getResetPasswordCallbackMockHandler = (
    overrideResponse?:
        | ResetPasswordCallback200
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0],
          ) => Promise<ResetPasswordCallback200> | ResetPasswordCallback200),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        "*/reset-password/:token",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getResetPasswordCallbackResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getListUserSessionsMockHandler = (
    overrideResponse?:
        | Session[]
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Session[]> | Session[]),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        "*/list-sessions",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getListUserSessionsResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getPostRevokeSessionMockHandler = (
    overrideResponse?:
        | PostRevokeSession200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<PostRevokeSession200> | PostRevokeSession200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/revoke-session",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getPostRevokeSessionResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getPostRevokeSessionsMockHandler = (
    overrideResponse?:
        | PostRevokeSessions200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<PostRevokeSessions200> | PostRevokeSessions200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/revoke-sessions",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getPostRevokeSessionsResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getPostRevokeOtherSessionsMockHandler = (
    overrideResponse?:
        | PostRevokeOtherSessions200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<PostRevokeOtherSessions200> | PostRevokeOtherSessions200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/revoke-other-sessions",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getPostRevokeOtherSessionsResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getLinkSocialAccountMockHandler = (
    overrideResponse?:
        | LinkSocialAccount200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<LinkSocialAccount200> | LinkSocialAccount200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/link-social",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getLinkSocialAccountResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getListUserAccountsMockHandler = (
    overrideResponse?:
        | ListUserAccounts200Item[]
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0],
          ) => Promise<ListUserAccounts200Item[]> | ListUserAccounts200Item[]),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        "*/list-accounts",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getListUserAccountsResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getGetDeleteUserCallbackMockHandler = (
    overrideResponse?:
        | GetDeleteUserCallback200
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0],
          ) => Promise<GetDeleteUserCallback200> | GetDeleteUserCallback200),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        "*/delete-user/callback",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetDeleteUserCallbackResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getPostUnlinkAccountMockHandler = (
    overrideResponse?:
        | PostUnlinkAccount200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<PostUnlinkAccount200> | PostUnlinkAccount200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/unlink-account",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getPostUnlinkAccountResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getPostRefreshTokenMockHandler = (
    overrideResponse?:
        | PostRefreshToken200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<PostRefreshToken200> | PostRefreshToken200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/refresh-token",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getPostRefreshTokenResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getPostGetAccessTokenMockHandler = (
    overrideResponse?:
        | PostGetAccessToken200
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<PostGetAccessToken200> | PostGetAccessToken200),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/get-access-token",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getPostGetAccessTokenResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getGetAccountInfoMockHandler = (
    overrideResponse?:
        | GetAccountInfo200
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0],
          ) => Promise<GetAccountInfo200> | GetAccountInfo200),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        "*/account-info",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetAccountInfoResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getGetOkMockHandler = (
    overrideResponse?:
        | GetOk200
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetOk200> | GetOk200),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        "*/ok",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetOkResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getGetErrorMockHandler = (
    overrideResponse?:
        | string
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<string> | string),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        "*/error",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetErrorResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};
export const getDefaultMock = () => [
    getSocialSignInMockHandler(),
    getGetSessionMockHandler(),
    getSignOutMockHandler(),
    getSignUpWithEmailAndPasswordMockHandler(),
    getSignInEmailMockHandler(),
    getResetPasswordMockHandler(),
    getGetVerifyEmailMockHandler(),
    getSendVerificationEmailMockHandler(),
    getChangeEmailMockHandler(),
    getChangePasswordMockHandler(),
    getUpdateUserMockHandler(),
    getDeleteUserMockHandler(),
    getRequestPasswordResetMockHandler(),
    getResetPasswordCallbackMockHandler(),
    getListUserSessionsMockHandler(),
    getPostRevokeSessionMockHandler(),
    getPostRevokeSessionsMockHandler(),
    getPostRevokeOtherSessionsMockHandler(),
    getLinkSocialAccountMockHandler(),
    getListUserAccountsMockHandler(),
    getGetDeleteUserCallbackMockHandler(),
    getPostUnlinkAccountMockHandler(),
    getPostRefreshTokenMockHandler(),
    getPostGetAccessTokenMockHandler(),
    getGetAccountInfoMockHandler(),
    getGetOkMockHandler(),
    getGetErrorMockHandler(),
];
