/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import type { ChangePassword200User } from "./changePassword200User";

export type ChangePassword200 = {
    /**
     * New session token if other sessions were revoked
     * @nullable
     */
    token?: string | null;
    user: ChangePassword200User;
};
