/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */

export type ChangePassword200User = {
    /** The unique identifier of the user */
    id: string;
    /** The email address of the user */
    email: string;
    /** The name of the user */
    name: string;
    /**
     * The profile image URL of the user
     * @nullable
     */
    image?: string | null;
    /** Whether the email has been verified */
    emailVerified: boolean;
    /** When the user was created */
    createdAt: string;
    /** When the user was last updated */
    updatedAt: string;
};
