/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.
 * OpenAPI spec version: 0.1.0
 */

export interface CreateEmailDto {
    /**
     * Sender of the email
     * @nullable
     */
    sender?: string | null;
    /**
     * Subject of the email
     * @nullable
     */
    subject?: string | null;
    /** Body of the email */
    body: string;
}
