/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */

export type DeleteUserBody = {
    /** The callback URL to redirect to after the user is deleted */
    callbackURL?: string;
    /** The user's password. Required if session is not fresh */
    password?: string;
    /** The deletion verification token */
    token?: string;
};
