/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Status message of the deletion process
 */
export type DeleteUser200Message = (typeof DeleteUser200Message)[keyof typeof DeleteUser200Message];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUser200Message = {
    User_deleted: "User deleted",
    Verification_email_sent: "Verification email sent",
} as const;
