/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import type { EmailAnalysisResultDtoCategory } from './emailAnalysisResultDtoCategory';
import type { ProductDto } from './productDto';
import type { IssueDto } from './issueDto';

export interface EmailAnalysisResultDto {
  /** Detected email category. */
  category: EmailAnalysisResultDtoCategory;
  /** Summary text for generic results. */
  summary?: string;
  /** One complaint per item. */
  complaints?: string[];
  /** Products requested by the customer. */
  products?: ProductDto[];
  /** Issues reported by the customer. */
  issues?: IssueDto[];
}
