/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.
 * OpenAPI spec version: 0.1.0
 */
import type { HealthControllerCheck503Info } from "./healthControllerCheck503Info";
import type { HealthControllerCheck503Error } from "./healthControllerCheck503Error";
import type { HealthControllerCheck503Details } from "./healthControllerCheck503Details";

export type HealthControllerCheck503 = {
    status?: string;
    /** @nullable */
    info?: HealthControllerCheck503Info;
    /** @nullable */
    error?: HealthControllerCheck503Error;
    details?: HealthControllerCheck503Details;
};
