/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Current status of the job
 */
export type JobDtoStatus = (typeof JobDtoStatus)[keyof typeof JobDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobDtoStatus = {
    CREATED: "CREATED",
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    COMPLETED: "COMPLETED",
} as const;
