/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import type { JobDtoStatus } from "./jobDtoStatus";

export interface JobDto {
    /** Unique job ID */
    id: string;
    /** Current status of the job */
    status: JobDtoStatus;
    /** User ID who created the job */
    userId: string;
    /** Email ID associated with this job */
    emailId: string;
    /**
     * Job start timestamp
     * @nullable
     */
    startedAt?: string | null;
    /**
     * Job completion timestamp
     * @nullable
     */
    completedAt?: string | null;
    /** Creation timestamp */
    createdAt: string;
    /**
     * Deletion timestamp if soft-deleted
     * @nullable
     */
    deletedAt?: string | null;
    /**
     * Associated JobResult ID, if completed
     * @nullable
     */
    resultId?: string | null;
}
