/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.
 * OpenAPI spec version: 0.1.0
 */
import type { JobResultDtoStatus } from "./jobResultDtoStatus";
import type { JobResultDtoOutput } from "./jobResultDtoOutput";

export interface JobResultDto {
    /** Unique JobResult ID */
    id: string;
    /** Associated Job ID */
    jobId: string;
    /** Status of the job result */
    status: JobResultDtoStatus;
    /** JSON output of the job */
    output: JobResultDtoOutput;
    /** Creation timestamp */
    createdAt: string;
    /**
     * Deletion timestamp if soft-deleted
     * @nullable
     */
    deletedAt?: string | null;
}
