/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Status of the job result
 */
export type JobResultDtoStatus = (typeof JobResultDtoStatus)[keyof typeof JobResultDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobResultDtoStatus = {
    SUCCESS: "SUCCESS",
    FAILURE: "FAILURE",
} as const;
