/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import type { LinkSocialAccountBodyIdToken } from "./linkSocialAccountBodyIdToken";

export type LinkSocialAccountBody = {
    /**
     * The URL to redirect to after the user has signed in
     * @nullable
     */
    callbackURL?: string | null;
    provider: string;
    /** @nullable */
    idToken?: LinkSocialAccountBodyIdToken;
    /** @nullable */
    requestSignUp?: boolean | null;
    /**
     * Additional scopes to request from the provider
     * @nullable
     */
    scopes?: unknown[] | null;
    /**
     * The URL to redirect to if there is an error during the link process
     * @nullable
     */
    errorCallbackURL?: string | null;
    /**
     * Disable automatic redirection to the provider. Useful for handling the redirection yourself
     * @nullable
     */
    disableRedirect?: boolean | null;
    /** @nullable */
    additionalData?: string | null;
};
