/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */

export type LinkSocialAccount200 = {
    /** The authorization URL to redirect the user to */
    url?: string;
    /** Indicates if the user should be redirected to the authorization URL */
    redirect: boolean;
    status?: boolean;
};
