/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import type { LinkSocialAccountBodyCallbackURL } from './linkSocialAccountBodyCallbackURL';
import type { LinkSocialAccountBodyIdToken } from './linkSocialAccountBodyIdToken';
import type { LinkSocialAccountBodyRequestSignUp } from './linkSocialAccountBodyRequestSignUp';
import type { LinkSocialAccountBodyScopes } from './linkSocialAccountBodyScopes';
import type { LinkSocialAccountBodyErrorCallbackURL } from './linkSocialAccountBodyErrorCallbackURL';
import type { LinkSocialAccountBodyDisableRedirect } from './linkSocialAccountBodyDisableRedirect';
import type { LinkSocialAccountBodyAdditionalData } from './linkSocialAccountBodyAdditionalData';

export type LinkSocialAccountBody = {
  /** The URL to redirect to after the user has signed in */
  callbackURL?: LinkSocialAccountBodyCallbackURL;
  provider: string;
  idToken?: LinkSocialAccountBodyIdToken;
  requestSignUp?: LinkSocialAccountBodyRequestSignUp;
  /** Additional scopes to request from the provider */
  scopes?: LinkSocialAccountBodyScopes;
  /** The URL to redirect to if there is an error during the link process */
  errorCallbackURL?: LinkSocialAccountBodyErrorCallbackURL;
  /** Disable automatic redirection to the provider. Useful for handling the redirection yourself */
  disableRedirect?: LinkSocialAccountBodyDisableRedirect;
  additionalData?: LinkSocialAccountBodyAdditionalData;
};
