/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */

/**
 * The URL to redirect the user to reset their password. If the token isn't valid or expired, it'll be redirected with a query parameter `?error=INVALID_TOKEN`. If the token is valid, it'll be redirected with a query parameter `?token=VALID_TOKEN
 */
export type RequestPasswordResetBodyRedirectTo = string | null;
