/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */

export type SignUpWithEmailAndPasswordBody = {
    /** The name of the user */
    name: string;
    /** The email of the user */
    email: string;
    /** The password of the user */
    password: string;
    /** The profile image URL of the user */
    image?: string;
    /** The URL to use for email verification callback */
    callbackURL?: string;
    /** If this is false, the session will not be remembered. Default is `true`. */
    rememberMe?: boolean;
};
