/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.
 * OpenAPI spec version: 0.1.0
 */

export interface SignupDto {
    name: string;
    email: string;
    password: string;
}
