/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */

/**
 * @nullable
 */
export type SocialSignInBodyIdToken = {
    /** ID token from the provider */
    token: string;
    /**
     * Nonce used to generate the token
     * @nullable
     */
    nonce?: string | null;
    /**
     * Access token from the provider
     * @nullable
     */
    accessToken?: string | null;
    /**
     * Refresh token from the provider
     * @nullable
     */
    refreshToken?: string | null;
    /**
     * Expiry date of the token
     * @nullable
     */
    expiresAt?: number | null;
} | null;
