/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import type { SocialSignInBodyIdTokenAnyOfNonce } from './socialSignInBodyIdTokenAnyOfNonce';
import type { SocialSignInBodyIdTokenAnyOfAccessToken } from './socialSignInBodyIdTokenAnyOfAccessToken';
import type { SocialSignInBodyIdTokenAnyOfRefreshToken } from './socialSignInBodyIdTokenAnyOfRefreshToken';
import type { SocialSignInBodyIdTokenAnyOfExpiresAt } from './socialSignInBodyIdTokenAnyOfExpiresAt';

export type SocialSignInBodyIdTokenAnyOf = {
  /** ID token from the provider */
  token: string;
  /** Nonce used to generate the token */
  nonce?: SocialSignInBodyIdTokenAnyOfNonce;
  /** Access token from the provider */
  accessToken?: SocialSignInBodyIdTokenAnyOfAccessToken;
  /** Refresh token from the provider */
  refreshToken?: SocialSignInBodyIdTokenAnyOfRefreshToken;
  /** Expiry date of the token */
  expiresAt?: SocialSignInBodyIdTokenAnyOfExpiresAt;
};
