/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import type { SocialSignInBodyCallbackURL } from './socialSignInBodyCallbackURL';
import type { SocialSignInBodyNewUserCallbackURL } from './socialSignInBodyNewUserCallbackURL';
import type { SocialSignInBodyErrorCallbackURL } from './socialSignInBodyErrorCallbackURL';
import type { SocialSignInBodyDisableRedirect } from './socialSignInBodyDisableRedirect';
import type { SocialSignInBodyIdToken } from './socialSignInBodyIdToken';
import type { SocialSignInBodyScopes } from './socialSignInBodyScopes';
import type { SocialSignInBodyRequestSignUp } from './socialSignInBodyRequestSignUp';
import type { SocialSignInBodyLoginHint } from './socialSignInBodyLoginHint';
import type { SocialSignInBodyAdditionalData } from './socialSignInBodyAdditionalData';

export type SocialSignInBody = {
  /** Callback URL to redirect to after the user has signed in */
  callbackURL?: SocialSignInBodyCallbackURL;
  newUserCallbackURL?: SocialSignInBodyNewUserCallbackURL;
  /** Callback URL to redirect to if an error happens */
  errorCallbackURL?: SocialSignInBodyErrorCallbackURL;
  provider: string;
  /** Disable automatic redirection to the provider. Useful for handling the redirection yourself */
  disableRedirect?: SocialSignInBodyDisableRedirect;
  idToken?: SocialSignInBodyIdToken;
  /** Array of scopes to request from the provider. This will override the default scopes passed. */
  scopes?: SocialSignInBodyScopes;
  /** Explicitly request sign-up. Useful when disableImplicitSignUp is true for this provider */
  requestSignUp?: SocialSignInBodyRequestSignUp;
  /** The login hint to use for the authorization code request */
  loginHint?: SocialSignInBodyLoginHint;
  additionalData?: SocialSignInBodyAdditionalData;
};
