/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import type { SocialSignInBodyIdToken } from "./socialSignInBodyIdToken";

export type SocialSignInBody = {
    /**
     * Callback URL to redirect to after the user has signed in
     * @nullable
     */
    callbackURL?: string | null;
    /** @nullable */
    newUserCallbackURL?: string | null;
    /**
     * Callback URL to redirect to if an error happens
     * @nullable
     */
    errorCallbackURL?: string | null;
    provider: string;
    /**
     * Disable automatic redirection to the provider. Useful for handling the redirection yourself
     * @nullable
     */
    disableRedirect?: boolean | null;
    /** @nullable */
    idToken?: SocialSignInBodyIdToken;
    /**
     * Array of scopes to request from the provider. This will override the default scopes passed.
     * @nullable
     */
    scopes?: unknown[] | null;
    /**
     * Explicitly request sign-up. Useful when disableImplicitSignUp is true for this provider
     * @nullable
     */
    requestSignUp?: boolean | null;
    /**
     * The login hint to use for the authorization code request
     * @nullable
     */
    loginHint?: string | null;
    /** @nullable */
    additionalData?: string | null;
};
