/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import type { UserDtoRole } from "./userDtoRole";

export interface UserDto {
    /** Unique user ID */
    id: string;
    /** Full name of the user */
    name: string;
    /** Email address of the user */
    email: string;
    /** Role of the user */
    role: UserDtoRole;
    /** Creation timestamp */
    createdAt: string;
    /**
     * Last update timestamp
     * @nullable
     */
    updatedAt?: string | null;
    /**
     * Deletion timestamp, if soft-deleted
     * @nullable
     */
    deletedAt?: string | null;
    /** IDs of jobs created by the user */
    jobs?: string[];
    /** IDs of emails uploaded by the user */
    emails?: string[];
}
