/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
    QueryFunction,
    QueryKey,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type { JobControllerGetJobsParams, JobDto, JobResultDto } from ".././models";

/**
 * @summary List jobs (filtered by user unless admin)
 */
export type jobControllerGetJobsResponse200 = {
    data: JobDto[];
    status: 200;
};

export type jobControllerGetJobsResponse401 = {
    data: void;
    status: 401;
};

export type jobControllerGetJobsResponseSuccess = jobControllerGetJobsResponse200 & {
    headers: Headers;
};
export type jobControllerGetJobsResponseError = jobControllerGetJobsResponse401 & {
    headers: Headers;
};

export type jobControllerGetJobsResponse =
    | jobControllerGetJobsResponseSuccess
    | jobControllerGetJobsResponseError;

export const getJobControllerGetJobsUrl = (params: JobControllerGetJobsParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0 ? `/api/jobs?${stringifiedParams}` : `/api/jobs`;
};

export const jobControllerGetJobs = async (
    params: JobControllerGetJobsParams,
    options?: RequestInit,
): Promise<jobControllerGetJobsResponse> => {
    const res = await fetch(getJobControllerGetJobsUrl(params), {
        ...options,
        method: "GET",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: jobControllerGetJobsResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as jobControllerGetJobsResponse;
};

export const getJobControllerGetJobsQueryKey = (params?: JobControllerGetJobsParams) => {
    return [`/api/jobs`, ...(params ? [params] : [])] as const;
};

export const getJobControllerGetJobsQueryOptions = <
    TData = Awaited<ReturnType<typeof jobControllerGetJobs>>,
    TError = void,
>(
    params: JobControllerGetJobsParams,
    options?: {
        query?: UseQueryOptions<Awaited<ReturnType<typeof jobControllerGetJobs>>, TError, TData>;
        fetch?: RequestInit;
    },
) => {
    const { query: queryOptions, fetch: fetchOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getJobControllerGetJobsQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof jobControllerGetJobs>>> = ({ signal }) =>
        jobControllerGetJobs(params, { signal, ...fetchOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof jobControllerGetJobs>>,
        TError,
        TData
    > & { queryKey: QueryKey };
};

export type JobControllerGetJobsQueryResult = NonNullable<
    Awaited<ReturnType<typeof jobControllerGetJobs>>
>;
export type JobControllerGetJobsQueryError = void;

/**
 * @summary List jobs (filtered by user unless admin)
 */

export function useJobControllerGetJobs<
    TData = Awaited<ReturnType<typeof jobControllerGetJobs>>,
    TError = void,
>(
    params: JobControllerGetJobsParams,
    options?: {
        query?: UseQueryOptions<Awaited<ReturnType<typeof jobControllerGetJobs>>, TError, TData>;
        fetch?: RequestInit;
    },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
    const queryOptions = getJobControllerGetJobsQueryOptions(params, options);

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Get detailed job information
 */
export type jobControllerGetJobByIdResponse200 = {
    data: JobDto;
    status: 200;
};

export type jobControllerGetJobByIdResponse401 = {
    data: void;
    status: 401;
};

export type jobControllerGetJobByIdResponse404 = {
    data: void;
    status: 404;
};

export type jobControllerGetJobByIdResponseSuccess = jobControllerGetJobByIdResponse200 & {
    headers: Headers;
};
export type jobControllerGetJobByIdResponseError = (
    | jobControllerGetJobByIdResponse401
    | jobControllerGetJobByIdResponse404
) & {
    headers: Headers;
};

export type jobControllerGetJobByIdResponse =
    | jobControllerGetJobByIdResponseSuccess
    | jobControllerGetJobByIdResponseError;

export const getJobControllerGetJobByIdUrl = (jobId: string) => {
    return `/api/jobs/${jobId}`;
};

export const jobControllerGetJobById = async (
    jobId: string,
    options?: RequestInit,
): Promise<jobControllerGetJobByIdResponse> => {
    const res = await fetch(getJobControllerGetJobByIdUrl(jobId), {
        ...options,
        method: "GET",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: jobControllerGetJobByIdResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as jobControllerGetJobByIdResponse;
};

export const getJobControllerGetJobByIdQueryKey = (jobId?: string) => {
    return [`/api/jobs/${jobId}`] as const;
};

export const getJobControllerGetJobByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof jobControllerGetJobById>>,
    TError = void,
>(
    jobId: string,
    options?: {
        query?: UseQueryOptions<Awaited<ReturnType<typeof jobControllerGetJobById>>, TError, TData>;
        fetch?: RequestInit;
    },
) => {
    const { query: queryOptions, fetch: fetchOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getJobControllerGetJobByIdQueryKey(jobId);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof jobControllerGetJobById>>> = ({
        signal,
    }) => jobControllerGetJobById(jobId, { signal, ...fetchOptions });

    return { queryKey, queryFn, enabled: !!jobId, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof jobControllerGetJobById>>,
        TError,
        TData
    > & { queryKey: QueryKey };
};

export type JobControllerGetJobByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof jobControllerGetJobById>>
>;
export type JobControllerGetJobByIdQueryError = void;

/**
 * @summary Get detailed job information
 */

export function useJobControllerGetJobById<
    TData = Awaited<ReturnType<typeof jobControllerGetJobById>>,
    TError = void,
>(
    jobId: string,
    options?: {
        query?: UseQueryOptions<Awaited<ReturnType<typeof jobControllerGetJobById>>, TError, TData>;
        fetch?: RequestInit;
    },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
    const queryOptions = getJobControllerGetJobByIdQueryOptions(jobId, options);

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Get job result output
 */
export type jobControllerGetJobResultResponse200 = {
    data: JobResultDto;
    status: 200;
};

export type jobControllerGetJobResultResponse401 = {
    data: void;
    status: 401;
};

export type jobControllerGetJobResultResponse404 = {
    data: void;
    status: 404;
};

export type jobControllerGetJobResultResponseSuccess = jobControllerGetJobResultResponse200 & {
    headers: Headers;
};
export type jobControllerGetJobResultResponseError = (
    | jobControllerGetJobResultResponse401
    | jobControllerGetJobResultResponse404
) & {
    headers: Headers;
};

export type jobControllerGetJobResultResponse =
    | jobControllerGetJobResultResponseSuccess
    | jobControllerGetJobResultResponseError;

export const getJobControllerGetJobResultUrl = (jobId: string) => {
    return `/api/jobs/${jobId}/result`;
};

export const jobControllerGetJobResult = async (
    jobId: string,
    options?: RequestInit,
): Promise<jobControllerGetJobResultResponse> => {
    const res = await fetch(getJobControllerGetJobResultUrl(jobId), {
        ...options,
        method: "GET",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: jobControllerGetJobResultResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as jobControllerGetJobResultResponse;
};

export const getJobControllerGetJobResultQueryKey = (jobId?: string) => {
    return [`/api/jobs/${jobId}/result`] as const;
};

export const getJobControllerGetJobResultQueryOptions = <
    TData = Awaited<ReturnType<typeof jobControllerGetJobResult>>,
    TError = void,
>(
    jobId: string,
    options?: {
        query?: UseQueryOptions<
            Awaited<ReturnType<typeof jobControllerGetJobResult>>,
            TError,
            TData
        >;
        fetch?: RequestInit;
    },
) => {
    const { query: queryOptions, fetch: fetchOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getJobControllerGetJobResultQueryKey(jobId);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof jobControllerGetJobResult>>> = ({
        signal,
    }) => jobControllerGetJobResult(jobId, { signal, ...fetchOptions });

    return { queryKey, queryFn, enabled: !!jobId, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof jobControllerGetJobResult>>,
        TError,
        TData
    > & { queryKey: QueryKey };
};

export type JobControllerGetJobResultQueryResult = NonNullable<
    Awaited<ReturnType<typeof jobControllerGetJobResult>>
>;
export type JobControllerGetJobResultQueryError = void;

/**
 * @summary Get job result output
 */

export function useJobControllerGetJobResult<
    TData = Awaited<ReturnType<typeof jobControllerGetJobResult>>,
    TError = void,
>(
    jobId: string,
    options?: {
        query?: UseQueryOptions<
            Awaited<ReturnType<typeof jobControllerGetJobResult>>,
            TError,
            TData
        >;
        fetch?: RequestInit;
    },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
    const queryOptions = getJobControllerGetJobResultQueryOptions(jobId, options);

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

    query.queryKey = queryOptions.queryKey;

    return query;
}
