/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  SubmitEmailResponseDto
} from '.././models';


export const getEmailControllerSubmitEmailResponseMock = (overrideResponse: Partial< SubmitEmailResponseDto > = {}): SubmitEmailResponseDto => ({data: {...{category: faker.helpers.arrayElement(['Other','Complaint','Product_Inquiry','Product_Support'] as const), summary: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), complaints: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined]), products: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({product_name: faker.string.alpha({length: {min: 10, max: 20}}), quantity: faker.number.float({min: undefined, max: undefined, fractionDigits: 2})})), undefined]), issues: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({product_name: faker.string.alpha({length: {min: 10, max: 20}}), issue: faker.string.alpha({length: {min: 10, max: 20}})})), undefined])},}, ...overrideResponse})


export const getEmailControllerSubmitEmailMockHandler = (overrideResponse?: SubmitEmailResponseDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SubmitEmailResponseDto> | SubmitEmailResponseDto), options?: RequestHandlerOptions) => {
  return http.post('*/emails', async (info) => {await delay(500);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getEmailControllerSubmitEmailResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getEmailsMock = () => [
  getEmailControllerSubmitEmailMockHandler()
]
