/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { EmailControllerSubmitEmail201 } from ".././models";

export const getEmailControllerSubmitEmailResponseMock = (
    overrideResponse: Partial<EmailControllerSubmitEmail201> = {},
): EmailControllerSubmitEmail201 => ({
    data: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
});

export const getEmailControllerSubmitEmailMockHandler = (
    overrideResponse?:
        | EmailControllerSubmitEmail201
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<EmailControllerSubmitEmail201> | EmailControllerSubmitEmail201),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/emails",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getEmailControllerSubmitEmailResponseMock(),
                ),
                { status: 201, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};
export const getEmailsMock = () => [getEmailControllerSubmitEmailMockHandler()];
