/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { JobDto } from ".././models";

export const getEmailControllerSubmitEmailResponseMock = (
    overrideResponse: Partial<JobDto> = {},
): JobDto => ({
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    status: faker.helpers.arrayElement(["CREATED", "PENDING", "PROCESSING", "COMPLETED"] as const),
    userId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    emailId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    startedAt: faker.helpers.arrayElement([
        faker.helpers.arrayElement([`${faker.date.past().toISOString().split(".")[0]}Z`, null]),
        undefined,
    ]),
    completedAt: faker.helpers.arrayElement([
        faker.helpers.arrayElement([`${faker.date.past().toISOString().split(".")[0]}Z`, null]),
        undefined,
    ]),
    createdAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
    deletedAt: faker.helpers.arrayElement([
        faker.helpers.arrayElement([`${faker.date.past().toISOString().split(".")[0]}Z`, null]),
        undefined,
    ]),
    resultId: faker.helpers.arrayElement([
        faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
        undefined,
    ]),
    ...overrideResponse,
});

export const getEmailControllerSubmitEmailMockHandler = (
    overrideResponse?:
        | JobDto
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<JobDto> | JobDto),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/emails",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getEmailControllerSubmitEmailResponseMock(),
                ),
                { status: 201, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};
export const getEmailsMock = () => [getEmailControllerSubmitEmailMockHandler()];
