/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  InstanceSettingsDto
} from '.././models';


export const getSettingsControllerGetInstanceSettingsResponseMock = (overrideResponse: Partial< InstanceSettingsDto > = {}): InstanceSettingsDto => ({hasOpenAIApiKey: faker.datatype.boolean(), isOpenAIApiKeyEnabled: faker.datatype.boolean(), ...overrideResponse})

export const getSettingsControllerUpdateInstanceApiKeyResponseMock = (overrideResponse: Partial< InstanceSettingsDto > = {}): InstanceSettingsDto => ({hasOpenAIApiKey: faker.datatype.boolean(), isOpenAIApiKeyEnabled: faker.datatype.boolean(), ...overrideResponse})

export const getSettingsControllerDeleteInstanceApiKeyResponseMock = (overrideResponse: Partial< InstanceSettingsDto > = {}): InstanceSettingsDto => ({hasOpenAIApiKey: faker.datatype.boolean(), isOpenAIApiKeyEnabled: faker.datatype.boolean(), ...overrideResponse})

export const getSettingsControllerUpdateInstanceApiKeyEnabledResponseMock = (overrideResponse: Partial< InstanceSettingsDto > = {}): InstanceSettingsDto => ({hasOpenAIApiKey: faker.datatype.boolean(), isOpenAIApiKeyEnabled: faker.datatype.boolean(), ...overrideResponse})


export const getSettingsControllerGetInstanceSettingsMockHandler = (overrideResponse?: InstanceSettingsDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<InstanceSettingsDto> | InstanceSettingsDto), options?: RequestHandlerOptions) => {
  return http.get('*/settings/instance', async (info) => {await delay(500);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSettingsControllerGetInstanceSettingsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getSettingsControllerUpdateInstanceApiKeyMockHandler = (overrideResponse?: InstanceSettingsDto | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<InstanceSettingsDto> | InstanceSettingsDto), options?: RequestHandlerOptions) => {
  return http.patch('*/settings/instance/api-key', async (info) => {await delay(500);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSettingsControllerUpdateInstanceApiKeyResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getSettingsControllerDeleteInstanceApiKeyMockHandler = (overrideResponse?: InstanceSettingsDto | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<InstanceSettingsDto> | InstanceSettingsDto), options?: RequestHandlerOptions) => {
  return http.delete('*/settings/instance/api-key', async (info) => {await delay(500);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSettingsControllerDeleteInstanceApiKeyResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getSettingsControllerUpdateInstanceApiKeyEnabledMockHandler = (overrideResponse?: InstanceSettingsDto | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<InstanceSettingsDto> | InstanceSettingsDto), options?: RequestHandlerOptions) => {
  return http.patch('*/settings/instance/api-key-enabled', async (info) => {await delay(500);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSettingsControllerUpdateInstanceApiKeyEnabledResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getSettingsMock = () => [
  getSettingsControllerGetInstanceSettingsMockHandler(),
  getSettingsControllerUpdateInstanceApiKeyMockHandler(),
  getSettingsControllerDeleteInstanceApiKeyMockHandler(),
  getSettingsControllerUpdateInstanceApiKeyEnabledMockHandler()
]
