/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  InstanceSettingsDto,
  UpdateInstanceApiKeyDto,
  UpdateInstanceApiKeyEnabledDto
} from '.././models';





/**
 * @summary Get instance-level settings (admin only)
 */
export type settingsControllerGetInstanceSettingsResponse200 = {
  data: InstanceSettingsDto
  status: 200
}

export type settingsControllerGetInstanceSettingsResponse401 = {
  data: void
  status: 401
}

export type settingsControllerGetInstanceSettingsResponse403 = {
  data: void
  status: 403
}
    
export type settingsControllerGetInstanceSettingsResponseSuccess = (settingsControllerGetInstanceSettingsResponse200) & {
  headers: Headers;
};
export type settingsControllerGetInstanceSettingsResponseError = (settingsControllerGetInstanceSettingsResponse401 | settingsControllerGetInstanceSettingsResponse403) & {
  headers: Headers;
};

export type settingsControllerGetInstanceSettingsResponse = (settingsControllerGetInstanceSettingsResponseSuccess | settingsControllerGetInstanceSettingsResponseError)

export const getSettingsControllerGetInstanceSettingsUrl = () => {


  

  return `/api/settings/instance`
}

export const settingsControllerGetInstanceSettings = async ( options?: RequestInit): Promise<settingsControllerGetInstanceSettingsResponse> => {
  
  const res = await fetch(getSettingsControllerGetInstanceSettingsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: settingsControllerGetInstanceSettingsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as settingsControllerGetInstanceSettingsResponse
}





export const getSettingsControllerGetInstanceSettingsQueryKey = () => {
    return [
    `/api/settings/instance`
    ] as const;
    }

    
export const getSettingsControllerGetInstanceSettingsQueryOptions = <TData = Awaited<ReturnType<typeof settingsControllerGetInstanceSettings>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof settingsControllerGetInstanceSettings>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSettingsControllerGetInstanceSettingsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof settingsControllerGetInstanceSettings>>> = ({ signal }) => settingsControllerGetInstanceSettings({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof settingsControllerGetInstanceSettings>>, TError, TData> & { queryKey: QueryKey }
}

export type SettingsControllerGetInstanceSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof settingsControllerGetInstanceSettings>>>
export type SettingsControllerGetInstanceSettingsQueryError = void


/**
 * @summary Get instance-level settings (admin only)
 */

export function useSettingsControllerGetInstanceSettings<TData = Awaited<ReturnType<typeof settingsControllerGetInstanceSettings>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof settingsControllerGetInstanceSettings>>, TError, TData>, fetch?: RequestInit}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSettingsControllerGetInstanceSettingsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update instance-level OpenAI API key (admin only)
 */
export type settingsControllerUpdateInstanceApiKeyResponse200 = {
  data: InstanceSettingsDto
  status: 200
}

export type settingsControllerUpdateInstanceApiKeyResponse401 = {
  data: void
  status: 401
}

export type settingsControllerUpdateInstanceApiKeyResponse403 = {
  data: void
  status: 403
}
    
export type settingsControllerUpdateInstanceApiKeyResponseSuccess = (settingsControllerUpdateInstanceApiKeyResponse200) & {
  headers: Headers;
};
export type settingsControllerUpdateInstanceApiKeyResponseError = (settingsControllerUpdateInstanceApiKeyResponse401 | settingsControllerUpdateInstanceApiKeyResponse403) & {
  headers: Headers;
};

export type settingsControllerUpdateInstanceApiKeyResponse = (settingsControllerUpdateInstanceApiKeyResponseSuccess | settingsControllerUpdateInstanceApiKeyResponseError)

export const getSettingsControllerUpdateInstanceApiKeyUrl = () => {


  

  return `/api/settings/instance/api-key`
}

export const settingsControllerUpdateInstanceApiKey = async (updateInstanceApiKeyDto: UpdateInstanceApiKeyDto, options?: RequestInit): Promise<settingsControllerUpdateInstanceApiKeyResponse> => {
  
  const res = await fetch(getSettingsControllerUpdateInstanceApiKeyUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateInstanceApiKeyDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: settingsControllerUpdateInstanceApiKeyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as settingsControllerUpdateInstanceApiKeyResponse
}




export const getSettingsControllerUpdateInstanceApiKeyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsControllerUpdateInstanceApiKey>>, TError,{data: UpdateInstanceApiKeyDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof settingsControllerUpdateInstanceApiKey>>, TError,{data: UpdateInstanceApiKeyDto}, TContext> => {

const mutationKey = ['settingsControllerUpdateInstanceApiKey'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof settingsControllerUpdateInstanceApiKey>>, {data: UpdateInstanceApiKeyDto}> = (props) => {
          const {data} = props ?? {};

          return  settingsControllerUpdateInstanceApiKey(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SettingsControllerUpdateInstanceApiKeyMutationResult = NonNullable<Awaited<ReturnType<typeof settingsControllerUpdateInstanceApiKey>>>
    export type SettingsControllerUpdateInstanceApiKeyMutationBody = UpdateInstanceApiKeyDto
    export type SettingsControllerUpdateInstanceApiKeyMutationError = void

    /**
 * @summary Update instance-level OpenAI API key (admin only)
 */
export const useSettingsControllerUpdateInstanceApiKey = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsControllerUpdateInstanceApiKey>>, TError,{data: UpdateInstanceApiKeyDto}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof settingsControllerUpdateInstanceApiKey>>,
        TError,
        {data: UpdateInstanceApiKeyDto},
        TContext
      > => {

      const mutationOptions = getSettingsControllerUpdateInstanceApiKeyMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Delete instance-level OpenAI API key (admin only)
 */
export type settingsControllerDeleteInstanceApiKeyResponse200 = {
  data: InstanceSettingsDto
  status: 200
}

export type settingsControllerDeleteInstanceApiKeyResponse401 = {
  data: void
  status: 401
}

export type settingsControllerDeleteInstanceApiKeyResponse403 = {
  data: void
  status: 403
}
    
export type settingsControllerDeleteInstanceApiKeyResponseSuccess = (settingsControllerDeleteInstanceApiKeyResponse200) & {
  headers: Headers;
};
export type settingsControllerDeleteInstanceApiKeyResponseError = (settingsControllerDeleteInstanceApiKeyResponse401 | settingsControllerDeleteInstanceApiKeyResponse403) & {
  headers: Headers;
};

export type settingsControllerDeleteInstanceApiKeyResponse = (settingsControllerDeleteInstanceApiKeyResponseSuccess | settingsControllerDeleteInstanceApiKeyResponseError)

export const getSettingsControllerDeleteInstanceApiKeyUrl = () => {


  

  return `/api/settings/instance/api-key`
}

export const settingsControllerDeleteInstanceApiKey = async ( options?: RequestInit): Promise<settingsControllerDeleteInstanceApiKeyResponse> => {
  
  const res = await fetch(getSettingsControllerDeleteInstanceApiKeyUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: settingsControllerDeleteInstanceApiKeyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as settingsControllerDeleteInstanceApiKeyResponse
}




export const getSettingsControllerDeleteInstanceApiKeyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsControllerDeleteInstanceApiKey>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof settingsControllerDeleteInstanceApiKey>>, TError,void, TContext> => {

const mutationKey = ['settingsControllerDeleteInstanceApiKey'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof settingsControllerDeleteInstanceApiKey>>, void> = () => {
          

          return  settingsControllerDeleteInstanceApiKey(fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SettingsControllerDeleteInstanceApiKeyMutationResult = NonNullable<Awaited<ReturnType<typeof settingsControllerDeleteInstanceApiKey>>>
    
    export type SettingsControllerDeleteInstanceApiKeyMutationError = void

    /**
 * @summary Delete instance-level OpenAI API key (admin only)
 */
export const useSettingsControllerDeleteInstanceApiKey = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsControllerDeleteInstanceApiKey>>, TError,void, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof settingsControllerDeleteInstanceApiKey>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getSettingsControllerDeleteInstanceApiKeyMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Enable or disable instance-level OpenAI API key usage
 */
export type settingsControllerUpdateInstanceApiKeyEnabledResponse200 = {
  data: InstanceSettingsDto
  status: 200
}

export type settingsControllerUpdateInstanceApiKeyEnabledResponse401 = {
  data: void
  status: 401
}

export type settingsControllerUpdateInstanceApiKeyEnabledResponse403 = {
  data: void
  status: 403
}
    
export type settingsControllerUpdateInstanceApiKeyEnabledResponseSuccess = (settingsControllerUpdateInstanceApiKeyEnabledResponse200) & {
  headers: Headers;
};
export type settingsControllerUpdateInstanceApiKeyEnabledResponseError = (settingsControllerUpdateInstanceApiKeyEnabledResponse401 | settingsControllerUpdateInstanceApiKeyEnabledResponse403) & {
  headers: Headers;
};

export type settingsControllerUpdateInstanceApiKeyEnabledResponse = (settingsControllerUpdateInstanceApiKeyEnabledResponseSuccess | settingsControllerUpdateInstanceApiKeyEnabledResponseError)

export const getSettingsControllerUpdateInstanceApiKeyEnabledUrl = () => {


  

  return `/api/settings/instance/api-key-enabled`
}

export const settingsControllerUpdateInstanceApiKeyEnabled = async (updateInstanceApiKeyEnabledDto: UpdateInstanceApiKeyEnabledDto, options?: RequestInit): Promise<settingsControllerUpdateInstanceApiKeyEnabledResponse> => {
  
  const res = await fetch(getSettingsControllerUpdateInstanceApiKeyEnabledUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateInstanceApiKeyEnabledDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: settingsControllerUpdateInstanceApiKeyEnabledResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as settingsControllerUpdateInstanceApiKeyEnabledResponse
}




export const getSettingsControllerUpdateInstanceApiKeyEnabledMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsControllerUpdateInstanceApiKeyEnabled>>, TError,{data: UpdateInstanceApiKeyEnabledDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof settingsControllerUpdateInstanceApiKeyEnabled>>, TError,{data: UpdateInstanceApiKeyEnabledDto}, TContext> => {

const mutationKey = ['settingsControllerUpdateInstanceApiKeyEnabled'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof settingsControllerUpdateInstanceApiKeyEnabled>>, {data: UpdateInstanceApiKeyEnabledDto}> = (props) => {
          const {data} = props ?? {};

          return  settingsControllerUpdateInstanceApiKeyEnabled(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SettingsControllerUpdateInstanceApiKeyEnabledMutationResult = NonNullable<Awaited<ReturnType<typeof settingsControllerUpdateInstanceApiKeyEnabled>>>
    export type SettingsControllerUpdateInstanceApiKeyEnabledMutationBody = UpdateInstanceApiKeyEnabledDto
    export type SettingsControllerUpdateInstanceApiKeyEnabledMutationError = void

    /**
 * @summary Enable or disable instance-level OpenAI API key usage
 */
export const useSettingsControllerUpdateInstanceApiKeyEnabled = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settingsControllerUpdateInstanceApiKeyEnabled>>, TError,{data: UpdateInstanceApiKeyEnabledDto}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof settingsControllerUpdateInstanceApiKeyEnabled>>,
        TError,
        {data: UpdateInstanceApiKeyEnabledDto},
        TContext
      > => {

      const mutationOptions = getSettingsControllerUpdateInstanceApiKeyEnabledMutationOptions(options);

      return useMutation(mutationOptions);
    }
    