/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { TokenResponseDto, UserDto } from ".././models";

export const getAuthControllerLoginResponseMock = (
    overrideResponse: Partial<TokenResponseDto> = {},
): TokenResponseDto => ({ ...overrideResponse });

export const getAuthControllerMeResponseMock = (
    overrideResponse: Partial<UserDto> = {},
): UserDto => ({
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    email: faker.string.alpha({ length: { min: 10, max: 20 } }),
    role: faker.helpers.arrayElement(["ADMIN", "USER"] as const),
    createdAt: `${faker.date.past().toISOString().split(".")[0]}Z`,
    updatedAt: faker.helpers.arrayElement([
        faker.helpers.arrayElement([`${faker.date.past().toISOString().split(".")[0]}Z`, null]),
        undefined,
    ]),
    deletedAt: faker.helpers.arrayElement([
        faker.helpers.arrayElement([`${faker.date.past().toISOString().split(".")[0]}Z`, null]),
        undefined,
    ]),
    jobs: faker.helpers.arrayElement([
        Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha({ length: { min: 10, max: 20 } }),
        ),
        undefined,
    ]),
    emails: faker.helpers.arrayElement([
        Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
            faker.string.alpha({ length: { min: 10, max: 20 } }),
        ),
        undefined,
    ]),
    ...overrideResponse,
});

export const getAuthControllerRefreshResponseMock = (
    overrideResponse: Partial<TokenResponseDto> = {},
): TokenResponseDto => ({ ...overrideResponse });

export const getAuthControllerSignupMockHandler = (
    overrideResponse?:
        | void
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/auth/signup",
        async (info) => {
            await delay(500);
            if (typeof overrideResponse === "function") {
                await overrideResponse(info);
            }
            return new HttpResponse(null, { status: 201 });
        },
        options,
    );
};

export const getAuthControllerLoginMockHandler = (
    overrideResponse?:
        | TokenResponseDto
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<TokenResponseDto> | TokenResponseDto),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/auth/login",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getAuthControllerLoginResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getAuthControllerMeMockHandler = (
    overrideResponse?:
        | UserDto
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserDto> | UserDto),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        "*/auth/me",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getAuthControllerMeResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};

export const getAuthControllerLogoutMockHandler = (
    overrideResponse?:
        | void
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/auth/logout",
        async (info) => {
            await delay(500);
            if (typeof overrideResponse === "function") {
                await overrideResponse(info);
            }
            return new HttpResponse(null, { status: 200 });
        },
        options,
    );
};

export const getAuthControllerRefreshMockHandler = (
    overrideResponse?:
        | TokenResponseDto
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<TokenResponseDto> | TokenResponseDto),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/auth/refresh",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getAuthControllerRefreshResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};
export const getAuthenticationMock = () => [
    getAuthControllerSignupMockHandler(),
    getAuthControllerLoginMockHandler(),
    getAuthControllerMeMockHandler(),
    getAuthControllerLogoutMockHandler(),
    getAuthControllerRefreshMockHandler(),
];
