/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    MutationFunction,
    QueryFunction,
    QueryKey,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type { LoginDto, RefreshTokenDto, SignupDto, TokenResponseDto, UserDto } from ".././models";

/**
 * @summary Register a new user
 */
export type authControllerSignupResponse201 = {
    data: void;
    status: 201;
};

export type authControllerSignupResponse400 = {
    data: void;
    status: 400;
};

export type authControllerSignupResponseSuccess = authControllerSignupResponse201 & {
    headers: Headers;
};
export type authControllerSignupResponseError = authControllerSignupResponse400 & {
    headers: Headers;
};

export type authControllerSignupResponse =
    | authControllerSignupResponseSuccess
    | authControllerSignupResponseError;

export const getAuthControllerSignupUrl = () => {
    return `/api/auth/signup`;
};

export const authControllerSignup = async (
    signupDto: SignupDto,
    options?: RequestInit,
): Promise<authControllerSignupResponse> => {
    const res = await fetch(getAuthControllerSignupUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(signupDto),
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: authControllerSignupResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as authControllerSignupResponse;
};

export const getAuthControllerSignupMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authControllerSignup>>,
        TError,
        { data: SignupDto },
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSignup>>,
    TError,
    { data: SignupDto },
    TContext
> => {
    const mutationKey = ["authControllerSignup"];
    const { mutation: mutationOptions, fetch: fetchOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof authControllerSignup>>,
        { data: SignupDto }
    > = (props) => {
        const { data } = props ?? {};

        return authControllerSignup(data, fetchOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type AuthControllerSignupMutationResult = NonNullable<
    Awaited<ReturnType<typeof authControllerSignup>>
>;
export type AuthControllerSignupMutationBody = SignupDto;
export type AuthControllerSignupMutationError = void;

/**
 * @summary Register a new user
 */
export const useAuthControllerSignup = <TError = void, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authControllerSignup>>,
        TError,
        { data: SignupDto },
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationResult<
    Awaited<ReturnType<typeof authControllerSignup>>,
    TError,
    { data: SignupDto },
    TContext
> => {
    const mutationOptions = getAuthControllerSignupMutationOptions(options);

    return useMutation(mutationOptions);
};
/**
 * @summary Login
 */
export type authControllerLoginResponse200 = {
    data: TokenResponseDto;
    status: 200;
};

export type authControllerLoginResponse401 = {
    data: void;
    status: 401;
};

export type authControllerLoginResponseSuccess = authControllerLoginResponse200 & {
    headers: Headers;
};
export type authControllerLoginResponseError = authControllerLoginResponse401 & {
    headers: Headers;
};

export type authControllerLoginResponse =
    | authControllerLoginResponseSuccess
    | authControllerLoginResponseError;

export const getAuthControllerLoginUrl = () => {
    return `/api/auth/login`;
};

export const authControllerLogin = async (
    loginDto: LoginDto,
    options?: RequestInit,
): Promise<authControllerLoginResponse> => {
    const res = await fetch(getAuthControllerLoginUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(loginDto),
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: authControllerLoginResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as authControllerLoginResponse;
};

export const getAuthControllerLoginMutationOptions = <TError = void, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authControllerLogin>>,
        TError,
        { data: LoginDto },
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogin>>,
    TError,
    { data: LoginDto },
    TContext
> => {
    const mutationKey = ["authControllerLogin"];
    const { mutation: mutationOptions, fetch: fetchOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof authControllerLogin>>,
        { data: LoginDto }
    > = (props) => {
        const { data } = props ?? {};

        return authControllerLogin(data, fetchOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type AuthControllerLoginMutationResult = NonNullable<
    Awaited<ReturnType<typeof authControllerLogin>>
>;
export type AuthControllerLoginMutationBody = LoginDto;
export type AuthControllerLoginMutationError = void;

/**
 * @summary Login
 */
export const useAuthControllerLogin = <TError = void, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authControllerLogin>>,
        TError,
        { data: LoginDto },
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationResult<
    Awaited<ReturnType<typeof authControllerLogin>>,
    TError,
    { data: LoginDto },
    TContext
> => {
    const mutationOptions = getAuthControllerLoginMutationOptions(options);

    return useMutation(mutationOptions);
};
/**
 * @summary Get current user info
 */
export type authControllerMeResponse200 = {
    data: UserDto;
    status: 200;
};

export type authControllerMeResponse401 = {
    data: void;
    status: 401;
};

export type authControllerMeResponseSuccess = authControllerMeResponse200 & {
    headers: Headers;
};
export type authControllerMeResponseError = authControllerMeResponse401 & {
    headers: Headers;
};

export type authControllerMeResponse =
    | authControllerMeResponseSuccess
    | authControllerMeResponseError;

export const getAuthControllerMeUrl = () => {
    return `/api/auth/me`;
};

export const authControllerMe = async (
    options?: RequestInit,
): Promise<authControllerMeResponse> => {
    const res = await fetch(getAuthControllerMeUrl(), {
        ...options,
        method: "GET",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: authControllerMeResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as authControllerMeResponse;
};

export const getAuthControllerMeQueryKey = () => {
    return [`/api/auth/me`] as const;
};

export const getAuthControllerMeQueryOptions = <
    TData = Awaited<ReturnType<typeof authControllerMe>>,
    TError = void,
>(options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>;
    fetch?: RequestInit;
}) => {
    const { query: queryOptions, fetch: fetchOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getAuthControllerMeQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerMe>>> = ({ signal }) =>
        authControllerMe({ signal, ...fetchOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof authControllerMe>>,
        TError,
        TData
    > & { queryKey: QueryKey };
};

export type AuthControllerMeQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerMe>>>;
export type AuthControllerMeQueryError = void;

/**
 * @summary Get current user info
 */

export function useAuthControllerMe<
    TData = Awaited<ReturnType<typeof authControllerMe>>,
    TError = void,
>(options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>;
    fetch?: RequestInit;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
    const queryOptions = getAuthControllerMeQueryOptions(options);

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Logout
 */
export type authControllerLogoutResponse200 = {
    data: void;
    status: 200;
};

export type authControllerLogoutResponse401 = {
    data: void;
    status: 401;
};

export type authControllerLogoutResponseSuccess = authControllerLogoutResponse200 & {
    headers: Headers;
};
export type authControllerLogoutResponseError = authControllerLogoutResponse401 & {
    headers: Headers;
};

export type authControllerLogoutResponse =
    | authControllerLogoutResponseSuccess
    | authControllerLogoutResponseError;

export const getAuthControllerLogoutUrl = () => {
    return `/api/auth/logout`;
};

export const authControllerLogout = async (
    options?: RequestInit,
): Promise<authControllerLogoutResponse> => {
    const res = await fetch(getAuthControllerLogoutUrl(), {
        ...options,
        method: "POST",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: authControllerLogoutResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as authControllerLogoutResponse;
};

export const getAuthControllerLogoutMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authControllerLogout>>,
        TError,
        void,
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogout>>,
    TError,
    void,
    TContext
> => {
    const mutationKey = ["authControllerLogout"];
    const { mutation: mutationOptions, fetch: fetchOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof authControllerLogout>>,
        void
    > = () => {
        return authControllerLogout(fetchOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type AuthControllerLogoutMutationResult = NonNullable<
    Awaited<ReturnType<typeof authControllerLogout>>
>;

export type AuthControllerLogoutMutationError = void;

/**
 * @summary Logout
 */
export const useAuthControllerLogout = <TError = void, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authControllerLogout>>,
        TError,
        void,
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationResult<Awaited<ReturnType<typeof authControllerLogout>>, TError, void, TContext> => {
    const mutationOptions = getAuthControllerLogoutMutationOptions(options);

    return useMutation(mutationOptions);
};
/**
 * @summary Refresh authentication token
 */
export type authControllerRefreshResponse200 = {
    data: TokenResponseDto;
    status: 200;
};

export type authControllerRefreshResponse401 = {
    data: void;
    status: 401;
};

export type authControllerRefreshResponseSuccess = authControllerRefreshResponse200 & {
    headers: Headers;
};
export type authControllerRefreshResponseError = authControllerRefreshResponse401 & {
    headers: Headers;
};

export type authControllerRefreshResponse =
    | authControllerRefreshResponseSuccess
    | authControllerRefreshResponseError;

export const getAuthControllerRefreshUrl = () => {
    return `/api/auth/refresh`;
};

export const authControllerRefresh = async (
    refreshTokenDto: RefreshTokenDto,
    options?: RequestInit,
): Promise<authControllerRefreshResponse> => {
    const res = await fetch(getAuthControllerRefreshUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(refreshTokenDto),
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: authControllerRefreshResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as authControllerRefreshResponse;
};

export const getAuthControllerRefreshMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authControllerRefresh>>,
        TError,
        { data: RefreshTokenDto },
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRefresh>>,
    TError,
    { data: RefreshTokenDto },
    TContext
> => {
    const mutationKey = ["authControllerRefresh"];
    const { mutation: mutationOptions, fetch: fetchOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof authControllerRefresh>>,
        { data: RefreshTokenDto }
    > = (props) => {
        const { data } = props ?? {};

        return authControllerRefresh(data, fetchOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type AuthControllerRefreshMutationResult = NonNullable<
    Awaited<ReturnType<typeof authControllerRefresh>>
>;
export type AuthControllerRefreshMutationBody = RefreshTokenDto;
export type AuthControllerRefreshMutationError = void;

/**
 * @summary Refresh authentication token
 */
export const useAuthControllerRefresh = <TError = void, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof authControllerRefresh>>,
        TError,
        { data: RefreshTokenDto },
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationResult<
    Awaited<ReturnType<typeof authControllerRefresh>>,
    TError,
    { data: RefreshTokenDto },
    TContext
> => {
    const mutationOptions = getAuthControllerRefreshMutationOptions(options);

    return useMutation(mutationOptions);
};
