
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  ADMIN: 'ADMIN',
  USER: 'USER'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const JobStatus = {
  CREATED: 'CREATED',
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED'
} as const

export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus]


export const JobResultStatus = {
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE'
} as const

export type JobResultStatus = (typeof JobResultStatus)[keyof typeof JobResultStatus]
