name: Build Frontend

on:
    push:
        branches:
            - main
            - develop
    pull_request:

env:
    node_version: ${{ vars.NODE_VERSION_FRONTEND }}
    working_directory: apps/frontend
    cache-dependency-path: apps/frontend/package-lock.json

jobs:
    build:
        name: Build Frontend
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup
              uses: ./.github/workflows/setup/
              with:
                  node_version: ${{ env.node_version }}
                  working-directory: ${{ env.working_directory }}
                  cache-dependency-path: ${{ env.cache-dependency-path }}

            - uses: actions/cache@v4
              with:
                  path: apps/frontend/.next/cache
                  # Generate a new cache whenever packages or source files change.
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('apps/frontend/package-lock.json') }}-${{ hashFiles('apps/frontend/**/*.js', 'apps/frontend/**/*.jsx', 'apps/frontend/**/*.ts', 'apps/frontend/**/*.tsx') }}
                  # If source files changed but packages didn't, rebuild from a prior cache.
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('apps/frontend/package-lock.json') }}-

            - name: Build Application
              run: npm run build
              working-directory: ${{ env.working_directory }}

            - name: Archive Build Artifacts
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: frontend-build-artifact
                  path: apps/frontend/.next
                  include-hidden-files: true
                  if-no-files-found: error
