name: Deploy

on:
    workflow_run:
        workflows:
            - Docker
        types:
            - completed
        branches:
            - develop

concurrency:
    group: deploy

jobs:
    sieve-deploy:
        name: Deploy to Remote Server
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only run if upstream workflows succeeded
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v7

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "Host *" >> ~/.ssh/config
                  echo -e "\tUserKnownHostsFile /dev/null" >> ~/.ssh/config
                  echo -e "\tStrictHostKeyChecking no" >> ~/.ssh/config
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa

            - name: Copy Config Files
              run: scp ./docker-compose.yml "${{ vars.REMOTE_USER }}@${{ vars.REMOTE_DOMAIN }}:${{ vars.WORK_DIR }}/"

            - name: Start Docker Compose on Remote Machine
              run: ssh "${{ vars.REMOTE_USER }}@${{ vars.REMOTE_DOMAIN }}" -- 'cd "${{ vars.WORK_DIR }}" && docker compose up -d --pull always --wait'

            - name: Copy schema.prisma to container
              run: cat ./apps/backend/prisma/schema.prisma | ssh "${{ vars.REMOTE_USER }}@${{ vars.REMOTE_DOMAIN }}" -- 'docker exec --interactive --user root sieve-deploy-backend-1 /bin/sh -c "cat > dist/prisma/schema.prisma"'

            - name: Prepare Database
              run: |
                cat <<EOF | ssh "${{ vars.REMOTE_USER }}@${{ vars.REMOTE_DOMAIN }}" -- 'docker exec --interactive --user root sieve-deploy-backend-1 /bin/sh'

                set -o errexit -o nounset -o pipefail

                cd dist

                if [ -f prisma.config.js ] && [ ! -f prisma.config.mjs ]; then
                  mv prisma.config.js prisma.config.mjs # Because Prisma does not like .js files only .mjs files
                fi

                pnpm dlx prisma db push
                node prisma/seed.js

                rm prisma/schema.prisma
                mv prisma.config.mjs prisma.config.js


                EOF

