name: Code Quality Checks Frontend

on:
    push:
        branches:
            - main
            - develop
    pull_request:
    workflow_dispatch:

jobs:
    linting:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup
              uses: ./.github/workflows/frontend_setup

            - name: Linting
              run: npm run lint
              working-directory: ./apps/frontend
