/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * SIEVE
 * This is the OpenAPI specification for the communication to the SIEVE backend via the REST-API. The SIEVE frontend and backend communicate via this API.

**Note**: Better Auth currently does not support customizing the tag names.
Therefore, the 'Default' tag is used for endpoints that are related to user authentication and session management.
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { HealthControllerCheck200 } from ".././models";

export const getHealthControllerCheckResponseMock = (
    overrideResponse: Partial<HealthControllerCheck200> = {},
): HealthControllerCheck200 => ({
    status: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
    ]),
    info: faker.helpers.arrayElement([
        {
            [faker.string.alphanumeric(5)]: {
                status: faker.string.alpha({ length: { min: 10, max: 20 } }),
            },
        },
        undefined,
    ]),
    error: faker.helpers.arrayElement([
        {
            [faker.string.alphanumeric(5)]: {
                status: faker.string.alpha({ length: { min: 10, max: 20 } }),
            },
        },
        undefined,
    ]),
    details: faker.helpers.arrayElement([
        {
            [faker.string.alphanumeric(5)]: {
                status: faker.string.alpha({ length: { min: 10, max: 20 } }),
            },
        },
        undefined,
    ]),
    ...overrideResponse,
});

export const getHealthControllerCheckMockHandler = (
    overrideResponse?:
        | HealthControllerCheck200
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0],
          ) => Promise<HealthControllerCheck200> | HealthControllerCheck200),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        "*/health",
        async (info) => {
            await delay(500);

            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === "function"
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getHealthControllerCheckResponseMock(),
                ),
                { status: 200, headers: { "Content-Type": "application/json" } },
            );
        },
        options,
    );
};
export const getHealthMock = () => [getHealthControllerCheckMockHandler()];
